### ISSUE TITLE
Add CLI support to generate default config

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/hermes#1095]
## Crate

`ibc-relayer-cli`

## Summary

Add a CLI command to generate and output a config file with defaults.

## Problem Definition

There is currently no way to create a default config file for hermes, so it would be nice to be able to generate a default config file that gives users a template to start with. In the future, we might also want to provide more config templates particularly for the tutorials in the hermes documentation and we could also provide a way to edit the config (maybe git style) using the CLI. 

## Proposal

We add the `config` command so that the interface is extensible to support future improvements such as config validation, etc. The `generate` subcommand could be interactive (based on the options it receives) to fill in parts of the default config template. 
```bash
$ hermes config generate [options]
# prints the config to stdout
```

## Acceptance Criteria

The `config generate` command must print a working config to stdout. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Partly superseded by #2187. Prioritizing to next milestone, could be useful project for @Farhad-Shabani soon.

**Comment by romac** [comment]
This has been available for a while with the `config auto` command.
