### ISSUE TITLE
Packet clearing function does not actually clear packets

### ISSUE THREAD

**Issue by mircea-c** [informalsystems/hermes#1404]
## Crate

Hermes

## Summary of Bug

Hermes attempts to clear pending packets, but fails to do so repeatedly:
```
Sep 30 12:03:01.645  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] clearing pending packets height=Some(Height { revision: 1, height: 1395619 })
 Sep 30 12:03:01.658 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:03:01.659 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:03:16.289  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)
 Sep 30 12:03:16.942  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] finished scheduling pending packets clearing height=Some(Height { revision: 1, height: 1395619 })
 Sep 30 12:05:31.991  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] clearing pending packets height=Some(Height { revision: 1, height: 1395639 })
 Sep 30 12:05:32.164 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:05:32.164 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:05:38.421  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)
 Sep 30 12:05:40.520  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] finished scheduling pending packets clearing height=Some(Height { revision: 1, height: 1395639 })
 Sep 30 12:07:50.010  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] clearing pending packets height=Some(Height { revision: 1, height: 1395659 })
 Sep 30 12:07:50.082 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:07:50.082 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:08:02.173  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)
 Sep 30 12:08:05.904  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] finished scheduling pending packets clearing height=Some(Height { revision: 1, height: 1395659 })
 Sep 30 12:09:28.531  INFO ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] clearing pending packets height=Some(Height { revision: 1, height: 1395679 })
 Sep 30 12:09:28.539 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
 Sep 30 12:09:28.539 DEBUG ThreadId(3549) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
```
Even more concerning, raw tx also fails to clear the same packets.

```
hermes@069cfad9b0e5:~$ hermes tx raw packet-recv iov-mainnet-ibc osmosis-1 transfer channel-15
Sep 30 12:03:20.812  INFO ThreadId(01) using default configuration from '/home/hermes/.hermes/config.toml'
Sep 30 12:03:20.825 DEBUG ThreadId(34) [osmosis-1] starting event monitor
Sep 30 12:03:20.833 DEBUG ThreadId(68) [iov-mainnet-ibc] starting event monitor
Sep 30 12:03:24.053 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:03:24.053 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:03:27.554  INFO ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)
Success: []
hermes@069cfad9b0e5:~$ hermes tx raw packet-recv iov-mainnet-ibc osmosis-1 transfer channel-15
Sep 30 12:04:27.279  INFO ThreadId(01) using default configuration from '/home/hermes/.hermes/config.toml'
Sep 30 12:04:27.290 DEBUG ThreadId(34) [osmosis-1] starting event monitor
Sep 30 12:04:27.298 DEBUG ThreadId(68) [iov-mainnet-ibc] starting event monitor
Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:04:30.818  INFO ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)
Success: []
```

No output as to what is actually happening.

## Version

0.7.2

## Steps to Reproduce

Connect hermes to `iov-mainnet-ibc` with `channel-2` allowed and `osmosis-1` with 'channel-15`

## Acceptance Criteria

Hermes is able to clear pending packets.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This is suboptimal logging standards on Hermes!

Each snippet has three important lines of log output, which are correlated among each other. For example, these ones:

> Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)
Sep 30 12:04:30.818  INFO ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] found unprocessed SendPacket events for [] (first 10 shown here; total=0)

The most important line of log output is the last. The important part, in particular, is the `0`. This means Hermes did not find any events to act upon, so there's no work to do, briefly. The full node for the **source** chain `osmosis-1` has no `SendPacket` **events** for the given port/channel id. The event system is the "ground truth", so the last line in the log is the relevant one, even if the lines above may claim something else.

---

For full context, the two other lines of log say the following:

> Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] packets that still have commitments on osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)

This line states that the source chain (osmisis-1) did not yet erase a certain number of commitments (`8` of them) from its on-chain store. So Osmosis does not yet know if the destination got its messages for these commitments, and it retains the commitments until it gets an Ack or a Timeout for them.

> Sep 30 12:04:27.309 DEBUG ThreadId(01) [osmosis-1:transfer/channel-15 -> iov-mainnet-ibc] recv packets to send out to iov-mainnet-ibc of the ones with commitments on source osmosis-1: 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943 (first 10 shown here; total=8)

This line states that: the **destination** chain, in this case `iov-mainnet-ibc`, claims to have `8` RecvPackets that it did not process yet (they're unreceived).


---

Takeaways: 
1. I think we will lower the log-level for the first two log lines to `trace`, to prevent misinterpretation.
2. We will also add an explicit log line saying "nothing to do" if there are zero events which Hermes can work with

**Comment by mircea-c** [comment]
Interesting. So how do we get rid of the commitments on the chain? Running `packet-ack` didn't do anything.

**Comment by adizere** [comment]
Hmm I'm not sure. I don't understand the details of the relation between events and the associated commitments. We'll engage with the sdk/ibc-go team to find out more about this.

**Comment by ancazamfir** [comment]
> Hmm I'm not sure. I don't understand the details of the relation between events and the associated commitments. We'll engage with the sdk/ibc-go team to find out more about this.

The packet commitments are stored in the application state. The packet data which is needed when building packet messages (`MsgRecvPacket` in this case) is stored in the Tx (stored in the blocks). In this case, after querying the app state on both src and dest, we know that there are 8 packets that were sent on osmosis but not received on iov.  So the next step is to retrieve the packet data from osmosis. We do this by calling `query_txs()` looking for a Tx that has generated the `SendPacket` event for the given channel and sequence number. In this case nothing is found. 
Some of the reasons could be:
- indexing is not enabled
- blocks have been pruned
- we have a regression in `query_txs()`

(Similar issue but for ack packets reported in #1377)
Also, imho we should not lower the debug level as the logs only occur on clear-packet heights and they help with debugging.
