### ISSUE TITLE
Packets not getting cleared (unknown request)

### ISSUE THREAD

**Issue by dhogaivannan** [informalsystems/hermes#1937]
## Crate

ibc-rs

## Summary of Bug

I'm using hermes relayer to send and receive packets between comdex (test-chain) and bandchain(testnet), the relayer was down for sometime and I'm trying to clear the unprocessed packets with `packet-ack` and `packet-recv` in v0.12.0-rc0 and tried `clear packets` from v0.12.0. While trying to clear, I face this issue. If the relayer has good uptime, 

```
ERROR ThreadId(07) send_tx{id=test-1}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet callback failed: cannot unmarshal packet data: proto: illegal wireType 6: unknown request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "176734"} 
```

## Version

v0.12.0-rc and v0.12.0

## Steps to Reproduce

Run a relayer between comdex and bandchain with different portids (bandoracle and oracle) and it's respective channel-version (bandchain-1), after having relayer down for sometime, clearing the unprocessed packets would throw the error.

## Acceptance Criteria

Packets getting cleared after the downtime.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Not sure how we could debug this. We would need (1) access to the test-chain and (2) expertise on comdex (since this seems more like a problem on the chain side or an incompatibility) but no one on the ibc-rs team has this. What SDK and ibc-go version is `test-1` running?

**Comment by dhogaivannan** [comment]
We can provide you RPC, gRPC and REST endpoints for this chain and regarding expertise @pratikasr can help you out.

SDK Version - v0.45.1
ibc-go - v2.0.2

**Comment by adizere** [comment]
Optimistically closing this as hopefully it was resolved in the meantime.

@dhogaivannan please let us know otherwise!
