### ISSUE TITLE
Could the `Cache` module's `latest_height` be encoded better? 

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#1941]
## Crate

 

`relayer`

## Summary

Could the `Cache` module's `latest_height` be encoded better? 

## Problem Definition

The `Cache` [type](https://github.com/informalsystems/ibc-rs/blob/aed240774df62b19099f796f2dd8459dabd72c88/relayer/src/cache.rs#L19-L24)'s `latest_height` field is encoded as a separate `MokaCache<(), Height>`. This makes it easy to associated a time-to-live value with the `Height`, but this perhaps feels a bit overkill just for that. Is there a lighter weight way to encode this? 

## Proposal

Just an open question that I thought might be useful to discuss: is there a lighter-weight way in which to encode the `Cache`'s `latest_height` field? 

Perhaps @adizere, @mzabaluev, and @soareschen could weigh in on this question.

## Acceptance Criteria

Discuss the proposed question and come up with an answer as to whether `latest_height` should be changed. If we decide yes, implement the discussed change. 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Here's a possible alternative -> 
A generic wrapper type that returns the `Some(inner)` value if the TTL hasn't expired and `None` otherwise ->
```rust
struct Cached<T> {
    inner: T,
    ttl: Duration,
}
```
And maybe we could also use this to wrap `moka`. And expose the following methods via a trait ->
```rust
trait Cache {
  type Type;
  type Error;

  fn insert(&mut self, Self::Type) -> Result<(), Self::Error>;
  fn get(&self) -> Option<&Self::Type>;
  fn invalidate(); 
}
```

**Comment by seanchen1991** [comment]
Quoting @soareschen:
> There is no need to create a specialized struct just for maps with empty key. The use of the top type (`()`) and the bottom type (`!`) for special casing is a common practice in functional programming and category theory. The Rust compiler generates monomorphized version of the structs instantiated from the generic parameters, and Rust should be able to optimize the specialized access for us for free.
In fact, look at the `HashSet` implementation of Rust: [https://doc.rust-lang.org/std/collections/struct.HashSet.html](https://doc.rust-lang.org/std/collections/struct.HashSet.html). It is simply implemented roughly as `type HashSet<T> = HashMap<T, ()>`. So we are essentially doing the same as core Rust is already doing.
