### ISSUE TITLE
New variant needed in the enum of `commitment_proof`

### ISSUE THREAD

**Issue by livelybug** [informalsystems/hermes#1945]
Hello,

The `CommitmentProof` has 4 variants [Exist, Nonexist, Batch, Compressed](https://github.com/informalsystems/ibc-rs/blob/aed240774df62b19099f796f2dd8459dabd72c88/proto/src/prost/std/ics23.rs#L56), none of them matches the structure of [the corresponding proof in Substrate](https://github.com/paritytech/substrate/blob/8df8d908c4d77a8dd19751784b6aca62159ddda8/client/rpc-api/src/state/helpers.rs#L27).

We use a temporary work-around [compose_ibc_merkle_proof](https://github.com/octopus-network/ibc-rs/blob/36b65032fc26018684eb5045c2de4e5b97fb723f/relayer/src/chain/substrate.rs#L1723) to insert the Substrate's proof into the `CommitmentProof` currently.

Is it possible to create a new variant in `CommitmentProof` for Substrate?

Thank you

**Comment by adizere** [comment]
I think it's possible. Changes to `CommitmentProof` would ideally go via this repo: https://github.com/confio/ics23/tree/master/rust upstream, then we'll update our dependency and the needed modifications will be available in ibc-rs also. Would you mind flagging the issue and motivation for the chance on ics23 repo?

**Comment by livelybug** [comment]
Thanks, it's flagged in https://github.com/confio/ics23/issues/80
