### ISSUE TITLE
Investigate missing gRPC APIs to allow efficient relaying of incentivized packets

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes#1965]
## Summary

This issue tracks the outstanding GRPC APIs that are required for the relayer to efficiently perform relaying on incentivized packets. Feedback needs to be given to https://github.com/cosmos/ibc-go/pull/276 before it is merged. The following APIs are missing:

## Query Counterparty Address (https://github.com/cosmos/ibc-go/issues/1132)

The relayer needs to be able to check whether it has already registered its counterparty address for a specific channel. Otherwise it can only blindly re-register its counterparty address before relaying which wastes transaction fees.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Closing this issue as 'done' since the gRPC APIs in question have been merged on the ibc-go side.
