### ISSUE TITLE
Write integration test for multi-hop channels

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes#1969]
## Summary

The test can probably be written as an `NaryConnectionTest<3>`. It seems like we probably also need to modify the core channel logic in `ibc-relayer` to make it possible to create channels with custom numbers of connection hops.

Depends on:
- [ ] https://github.com/cosmos/ibc/pull/836

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Closing this as the listed PR that this work depends on has been closed as un-planned.
