### ISSUE TITLE
gaiad and java undeclared test dependencies

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#2041]
## Summary of Bug
`gaiad` and `java` are undeclared dependencies to properly run our tests.

## Version

v0.13.0

## Acceptance Criteria
It is clear that `gaiad` and `java` need to be installed for tests.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
How do you suggest we go about making clear that both executables need to be available for tests?

I was thinking we could perhaps check for that in the `build.rs` script when building in `test` mode by doing the check when the env var `CARGO_CFG_TEST` is set but that apparently does not work: https://github.com/rust-lang/cargo/issues/4789

Any other idea?

**Comment by plafer** [comment]
A quick win/hack would be to simply add a section (e.g. `Test dependencies`) to the README, with pointers to how to install each? 

Or one step further would be to have an interactive script that installs both if they're not installed? But that's a bit more work to make sure we support all platforms/environments properly...
