### ISSUE TITLE
Add Hermes "bulk" key restore feature

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#2088]
## Problem statement

Currently, relayer operators who run on multiple networks need to do repeated `hermes keys restore` command invocations to set up their wallets for each chain in particular. See this [file for an example](https://github.com/notional-labs/notional/tree/master/relaying/hermes#omni-chain-hermes-quickstart).

> hermes keys restore cosmoshub-4 -m "12 or 24 magic words"
hermes keys restore emoney-3 -m "12 or 24 magic words"
hermes keys restore akashnet-2 -m "12 or 24 magic words"
hermes keys restore regen-1 -m "12 or 24 magic words"
hermes keys restore osmosis-1 -m "12 or 24 magic words"
hermes keys restore microtick-1 -m "12 or 24 magic words"
hermes keys restore bitcanna-1 -m "12 or 24 magic words"
hermes keys restore sentinelhub-2 -m "12 or 24 magic words"
hermes keys restore irishub-1 -m "12 or 24 magic words"
hermes keys restore iov-mainnet-ibc -m" 12 or 24 magic words" -p "m/44'/234'/0'/0/0"
hermes keys restore crypto-org-chain-mainnet-1 -m "12 or 24 magic words" -p "m/44'/394'/0'/0/0"
hermes keys restore core-1 -m "12 or 24 magic words" -p "m/44'/750'/0'/0/0"
hermes keys restore columbus-5 -m "12 or 24 magic words" -p "m/44'/330'/0'/0/0"
hermes keys restore kava-9 -m "12 or 24 magic words" -p "m/44'/459'/0'/0/0"
hermes keys restore impacthub-3 -m "12 or 24 magic words"

## Solution requirements
Most often, the mnemonic is the same across all chains. We should provide a way to __restore a key across all chains present in the config.toml from the same mnemonic__.

### Solution suggestions

The solution requirements would be met with a new CLI as follows:

```
hermes keys restore-all -m "12 or 24 magic words"
```

Where the `restore-all` would be a new subcommand of `keys` namespace. The alternative is to have an option `--all` accepted as part of the usual `keys restore` command:

```
hermes keys restore -m "12 or 24 magic words" --all
```

Unclear which is more simple among `keys restore-all` and `keys restore --all`. The former would be more intuitive.

**Comment by seanchen1991** [comment]
I'm personally more in favor of the `--all` flag option. 

> Just a note that doing this requires that we add the HD path to every chain config.

What is the "HD path" that you're referring to here?

**Comment by romac** [comment]
The [HD path](https://hub.cosmos.network/main/resources/hd-wallets.html) is the argument to `-p` that we currently have to pass if it's not the [default Cosmos/ATOM one](https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path). 

Because some chains may use a non-default path, we have to be able to specify the path somehow, ie. in the config.

**Comment by adizere** [comment]
> The [HD path](https://hub.cosmos.network/main/resources/hd-wallets.html) is the argument to `-p` that we currently have to pass if it's not the [default Cosmos/ATOM one](https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path).
> 
> Because some chains may use a non-default path, we have to be able to specify the path somehow, ie. in the config.

Good point!

Since this requires config changes and it's only a nice-to-have, I deprioritized it.

**Comment by adizere** [comment]
One suggestion: Let's implement the first version of this new CLI without configuration changes. That is, let's not add a new config.toml field for the HD path as part of this new CLI. Instead, it's fine if the new CLI assumes that _all_ chains have the same [default HD path](https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path). I am confirming with operators that this approach is fine.

**Comment by romac** [comment]
> One suggestion: Let's implement the first version of this new CLI without configuration changes. That is, let's not add a new config.toml field for the HD path as part of this new CLI. Instead, it's fine if the new CLI assumes that all chains have the same [default HD path](https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path). I am confirming with operators that this approach is fine.

I'd rather we don't implement this at all rather than doing it half-way. I don't really see the issue with writing a simple shell script for doing this, like operators have been doing up to now, while preserving the flexibility to set the HD path for each chain in the restore command.

That said, I am not against adding the HD path to the config and implement the bulk restore functionality, but I would rank it as very low priority.

**Comment by adizere** [comment]
Thanks for the input Romain! I see your point. Since the user impact doesn't seem to be significant, and a proposer solution involves configuration changes, I'll go ahead and close this as deprioritized/not important.
