### ISSUE TITLE
Collate commitment IDs in output of `query packet`

### ISSUE THREAD

**Issue by mzabaluev** [informalsystems/hermes#2142]
## Summary

Collate numerically adjacent commitment IDs in output of `query packet` subcommands.

## Problem Definition

When the set of pending packets on a channel is large and there are many pending commitments with consecutive IDs (which should be expected in normal channel operations), the output may become unfriendly to read for a human.

## Proposal

Collate adjacent ID numbers in non-JSON output of commands under `query packet`, like `[100-200, 202, 207]`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Done in https://github.com/informalsystems/hermes/pull/2847
