### ISSUE TITLE
Refactor `Ics26Context`: composition over inheritance

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#2184]
[`Ics26Context`](https://github.com/informalsystems/ibc-rs/blob/5b3ad097942a33fd18a7cf36f71c6622f215f801/modules/src/core/ics26_routing/context.rs#L27) currently "inherits" `Client{Reader,Keeper}`, `Connection{Reader,Keeper}`, `Channel{Reader,Keeper}`, `PortReader` and `Ics20Context`. This forces the implementing struct to be a "god object" which knows how to deal with all of IBC concerns.

A suggested way to improve on this design would be to have `Ics26Context` be a struct that composes these in a way similar to:

```rust
struct Ics26Context {
    client_reader: &dyn ClientReader,
    client_keeper: &dyn ClientKeeper,
    connection_reader: &dyn ConnectionReader,
    ...
}
```

The implementor is then free to implement all the traits how they see fit, and put them together in an `Ics26Context` before being passed to [`deliver()`](https://github.com/informalsystems/ibc-rs/blob/5b3ad097942a33fd18a7cf36f71c6622f215f801/modules/src/core/ics26_routing/handler.rs#L27).

This thread is meant for discussing other ideas on how to refactor `Ics26Context`, or go with the above suggestion.

Independently discussed with @hu55a1n1 and @romac, with ideas contributed by both.

**Comment by hu55a1n1** [comment]
Thanks for initiating this discussion @plafer! 👍 I like the idea of favouring composition over inheritance and the proposed
design looks great, but I think it would be better if the design allowed users to choose how they wanted to deal with
the ownership/lifetime of the readers and keepers. (i.e. should `client_reader` be a `&dyn ClientReader`, `&mut dyn ClientReader` or `ClientReader`)

We could address this problem quite easily using generics ->

```rust
#[derive(Debug)]
struct Ics26Context<CR, CK /* , ... */> {
    client_reader: CR,
    client_keeper: CK,
    // ...
}
```

But here again the API seems to assume that `CR` and `CK` are different types/instances.

Here's an alternative design -

```rust
pub trait Ics26Context {
    type ClientReader: ClientReader;
    type ClientKeeper: ClientKeeper;
    // ...

    /// Returns a non-mutable reference to the context's `ClientReader`.
    fn client_reader(&self) -> &Self::ClientReader;

    /// Returns a mutable reference to the context's `ClientKeeper`.
    /// (a non-mutable reference to a keeper wouldn't be very useful)
    fn client_keeper(&mut self) -> &mut Self::ClientKeeper;
    // ...
}
```

This allows users to decide how they want to deal with the ownership of readers/keepers and users could use the same
type/instance for readers and keepers. An additional benefit is that it allows us (as lib writers) to provide default
impls for trait methods that use these readers/keepers.

**Comment by hu55a1n1** [comment]
I also think the readers/keepers can be broken down into smaller and more specific traits based on their usage in the
codebase. This is to address a problem that I encountered during my work on the ICS20 implementation.

The `Ics20Keeper` is currently defined like so, with `ChannelKeeper` as a super-trait ->

```rust
pub trait Ics20Keeper: ChannelKeeper + PortKeeper {}
```

But it only ever uses two methods from the `ChannelKeeper` trait ->

```rust
pub trait ChannelKeeper {
    fn store_packet_commitment(
        &mut self,
        key: (PortId, ChannelId, Sequence),
        commitment: PacketCommitment,
    ) -> Result<(), Error>;

    fn store_next_sequence_send(
        &mut self,
        port_channel_id: (PortId, ChannelId),
        seq: Sequence,
    ) -> Result<(), Error> {
        self.ibc_store
            .lock()
            .unwrap()
            .next_sequence_send
            .insert(port_channel_id, seq);
        Ok(())
    }

    // ...
}
```

This means that the implementor would write a lot of unnecessary boilerplate for the remaining trait methods
with `unimplemented!()` bodies. The API itself isn't clearly communicating the exact dependencies of the `Ics20Keeper`.

One solution to this problem could be to not depend on the `ChannelKeeper` trait at all and define those methods in
the `Ics20Keeper` trait itself, but the problem with this approach is that some ICS20 functions need to be able to call
core IBC methods like `send_packet()` which need a type implementing `ChannelKeeper`.

So I propose we break down the reader/keeper traits into smaller composable traits and use them as super-traits. The
granularity of which methods to include in these traits can be determined based on their current usage in the codebase.
We also need to use more specific trait bounds in core handlers to make them easier to use. e.g.

```rust
pub trait PacketCommitmentKeeper {
    fn store_packet_commitment(
        &mut self,
        key: (PortId, ChannelId, Sequence),
        commitment: PacketCommitment,
    ) -> Result<(), Error>;
}

pub trait PacketSequenceKeeper {
    fn store_next_sequence_send(
        &mut self,
        port_channel_id: (PortId, ChannelId),
        seq: Sequence,
    ) -> Result<(), Error> {
        self.ibc_store
            .lock()
            .unwrap()
            .next_sequence_send
            .insert(port_channel_id, seq);
        Ok(())
    }
}

/// ...

pub trait ChannelKeeper: PacketCommitmentKeeper + PacketSequenceKeeper /* + ... */ {}

pub fn send_packet<Ctx: PacketCommitmentKeeper + PacketSequenceKeeper>(_ctx: Ctx, _packet: Packet) -> HandlerResult<PacketResult, Error> {}
```
