### ISSUE TITLE
Packet proof of `TimeoutOnClose` packets for ordered channels is wrong

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#2243]
## Summary of Bug
Looking at `ChainEndpoint::proven_packet(PacketMsgType::TimeoutOnClose)`  for `CosmosSdkChain`, we build a `ReceiptPath`, which is only correct if the channel is unordered. For ordered channels, we should query the `SeqRecvsPath`  to build the proof.

@ancazamfir:
> indeed we need to do like [this](https://github.com/informalsystems/ibc-rs/blob/eae0afd90d020af6a2e5feaa681dacf1294c7b8d/relayer/src/chain/cosmos.rs#L1447) for this case.

## Version

v0.15.0

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment]
Fixed in https://github.com/informalsystems/hermes/pull/3065
