### ISSUE TITLE
`ChainEndpoint::query_next_sequence_receive()` should include a height in no-proof case

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#2244]
## Summary of Bug
With the refactor of #2226, I realized that the without proof didn't specify a height, whereas the query with proof (formerly in `proven_packet()`) did. gRPC queries now support heights (#1088). We should remember to add the height in the gRPC request in `ChainEndpoint::query_next_sequence_receive()` when we address #1088.

Depends on: #2226
Related: #1088

v0.15.0
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Fixed in #3662
