### ISSUE TITLE
Interchain queries support

### ISSUE THREAD

**Issue by asalzmann** [informalsystems/hermes#2362]
## Summary

Add support for interchain queries. Spec: https://github.com/cosmos/ibc/pull/735

## Problem Definition

Interchain queries (cross-chain queries) are being used by projects across the ecosystem, and the spec is being finalized. This will allow chains to query state on other chains. 

## Proposal

Add support for cross-chain queries

## Acceptance Criteria

Relaying proven query results at specific block heights between chains.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thank you for flagging this requirement. Could you please add details about the implementation details of interchain queries?
- where should we expect to find the protobuf files
- the timeline for when this feature is expected to be implemented and integrated into a chain
    - will interchain queries be a module, bundled with `ibc-go` into a SDK binary?

Any demos or recipes for testing would also be appreciated!

**Comment by adizere** [comment]
Hi @asalzmann can you confirm this PR #2709 is the appropriate one for your use-case?

**Comment by adizere** [comment]
Closing this issue, as it is a duplicate of #2707.
