### ISSUE TITLE
Is the `rust-toolchain.toml` file necessary? 

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2611]
## Problem
I get a lot of `proc macro not expanded` errors from rust-analyzer in my editor when working in ibc-rs. This turns out to be because the repo's `rust-toolchain.toml` file overrides the toolchain I'm using when I'm in the repo to `1.63-aarch64-apple-darwin`. In every other context, my toolchain defaults to `x86_64-apple-darwin` such that I don't get any errors regarding proc macros not being expanded. 

I suppose there are a couple of ways this could be addressed:
- Figure out how to configure the `rust-toolchain.toml` file such that it sets the version of Rust to `1.63-x86_64-apple-darwin` when I'm in the ibc-rs repo.
- Remove the file entirely. I don't know whether this is a good idea or not, i.e. would issues arise as a result of everyone possibly developing using different versions of Rust? 

As it stands, I have to delete the file and rebuild the project every time it gets pulled in again from GitHub. Adding the file to the repo's `.gitignore` doesn't seem to make sense; at that point I suspect we might as well remove it entirely. 

## Acceptance Criteria

- [x] Figure out the most acceptable way to address this problem.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by mzabaluev** [comment]
I think this can help in your particular issue:

```
USAGE:
    rustup set default-host <host_triple>
```

Besides that, I don't know if there is a benefit in fixing the toolchain override.
The MSRV is maintained through `Cargo.toml` and `clippy.toml`.

**Comment by romac** [comment]
Yeah let's remove it then
