### ISSUE TITLE
What to do about insufficient funds in relayer wallet?

### ISSUE THREAD

**Issue by Venusdev228** [informalsystems/hermes#2686]
When I try to execute the command "hermes tx ft-transfer --dst-chain testmun --src-chain cosmoshub-4 --src-port transfer --src-channel channel-412 --amount 1000", I meet the the error.
Please give me some recommendation.

ERROR transfer error: failed while submitting the Transfer message to chain cosmoshub-4: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 0: 0samoleans is smaller than 1000samoleans: insufficient funds", details: [], metadata: MetadataMap { headers: {"date": "Mon, 03 Oct 2022 00:16:47 GMT", "content-type": "application/grpc", "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400", "x-cosmos-block-height": "12293020", "cf-cache-status": "DYNAMIC", "report-to": "{\"endpoints\":[{\"url\":\"https:\/\/a.nel.cloudflare.com\/report\/v3?s=MPi0baSLWoVTHWx8JZRFRg3Yos8oxdUtaJVWXbznmSLdtgI5QFU6TrcirPABMXeq0ZP5lz0Rf3Cmpln%2BdkX2cW9tWNjSqzUBt1KQ8TBHoCurKyBnxaRRhD3%2FXvOw8ntU7jl0IAvLGuMzzzOeufeh\"}],\"group\":\"cf-nel\",\"max_age\":604800}", "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", "server": "cloudflare", "cf-ray": "75417db42c2580cb-NRT"} }

**Comment by adizere** [comment]
In these logs, you are submitting a transaction to `cosmoshub-4` network. The wallet your relayer is using has no funds to pay for that transaction. See `hermes keys list --chain cosmoshub-4`, ref [guide here](https://hermes.informal.systems/commands/keys/index.html#list-keys). Specifically, you're trying to pay with `samoleans`, but your wallet has `0 samoleans`. Furthermore, `cosmoshub-4` does not accept samoleans, you need uatoms ($ATOM) to pay for transaction on this network.

So two problems to solve:

- fund you wallet with atoms
- change the relayer configuration for `comoshub-4` to use `uatoms` for fees, example: [Cephalopod config.toml](https://github.com/cephalopodequipment/config/blob/f77c9c865f2d1207ba6d66fe6a505a91995731ed/hermes/manual.toml#L27)
