### ISSUE TITLE
Hermes Guide(v1.0.0) needs some minor fixations

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/hermes#2694]
## Summary of Bug

Following the Hermes guide step by step, I came across some minor findings that may affect users' experience
​
1. In [How to run](https://hermes.informal.systems/tutorials/local-chains/gaiad-manager.html#how-to-run) section, the correct command for `install gm` is:
​
```bash
git clone https://github.com/informalsystems/hermes.git
hermes/scripts/gm/bin/gm install
```
​
2. In [adding private keys to the chain](https://hermes.informal.systems/tutorials/local-chains/start.html#adding-private-keys-to-the-chains), the command should be updated to the below one:
​
```bash
gm keys
```
​
3. In [Client identifier](https://hermes.informal.systems/tutorials/local-chains/identifiers.html#1-client-identifiers), the log on my console does not correspond to the one in the tutorial. The `height` field does not appear within `Attributes`. Here is a sample output log:
​
```bash
SUCCESS CreateClient(
    CreateClient(
        Attributes {
            client_id: ClientId(
                "07-tendermint-0",
            ),
            client_type: Tendermint,
            consensus_height: Height {
                revision: 0,
                height: 476,
            },
        },
    ),
)
```
​
4. The naming of subcommands in the CLI does not appear consistent for source and destination chains. Different pairs of  --dst-chain/--src-chain,--a-chain/--b-chain, --sender-chain/--receiver-chain have been used. 
Also, some are outdated, and the correct commands would be as below:
- For step 9 of **[Relay packets on multiple paths](https://hermes.informal.systems/tutorials/local-chains/relay-paths/multiple-paths.html#relay-packets-on-multiple-paths):**
​
```bash
hermes tx conn-init --dst-chain ibc-1 --src-chain ibc-0 --dst-client 07-tendermint-0 --src-client 07-tendermint-0
```
​
- For the [Connection Identifiers](https://hermes.informal.systems/tutorials/local-chains/identifiers.html#2-connection-identifiers) section of **[Identifiers](https://hermes.informal.systems/tutorials/local-chains/identifiers.html#identifiers)**
​
```bash
hermes tx ft-transfer --dst-chain ibc-1 --src-chain ibc-0 --src-port transfer --src-channel channel-0 --amount 9999 --timeout-height-offset 1000 --number-msgs 2
```

## Version

hermes 1.0.0+ed4dd8c (Run by downloading the latest binary) 

gm v0.1.3

gaiad v7.0.3

rustc 1.63.0

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
It looks like most of these issues have been addressed, save for having to change the repo's name from `ibc-rs` to `hermes`; thanks for catching that one! 

These changes haven't been pushed to the live site yet. It was an oversight on our part to refer you to the live site; it would have made for a smoother onboarding experience had you built the most up-to-date version of the guide locally and followed that.
