### ISSUE TITLE
Undo the changes introduced in #2332  #2412 and #2483

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#2715]
Follow-up to #2710.

The idea is to undo (some of) the changes introduced in the following PRs, to keep the definitions in `ibc-relayer-types` as canonical as possible, without object safety concerns.

This means that we have to re-introduce the `Any[Header,Client,etc.]` enums in the `relayer-types` crate, but perhaps there is a better design to be found.

  - [ ] #2332 
  - [ ] #2412
  - [ ] #2483

**Comment by adizere** [comment]
Seems done, thank you Romain!

**Comment by romac** [comment]
It's not actually done, but we may want to discuss which parts of this we actually want to revert. Not a priority right now though so let's push it to 1.3.

**Comment by romac** [comment]
Done in #3671
