### ISSUE TITLE
Ibc-Go module at version '4.0.0' does not meet compatibility requirements >=1.1, <=3

### ISSUE THREAD

**Issue by kooric** [informalsystems/hermes#2734]
hermes(v1.0.0) don't support Ibc-Go>v4?

**Comment by romac** [comment]
Which version of Hermes are you using?

**Comment by romac** [comment]
You can disregard the warning, Hermes v1.0.0 is actually compatible with IBC-Go v4 but we forgot to update the compatibility check in Hermes v1.0.0.

The next release of Hermes (v1.1.0) will be compatible with IBC-Go v5 and the compatibility check is now up to date :)

Thanks for flagging this!
