### ISSUE TITLE
Replace the types in ibc-relayer-types with the types in ibc-rs

### ISSUE THREAD

**Issue by DaviRain-Su** [informalsystems/hermes#2747]
## Problem Definition

Most of the types defined in `ibc-relayer-types` that `herme`s relayer depends on exist in `ibc-rs`, should we refer directly to the types defined in `ibc-rs`, we don't want to have two definitions of the same types

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
This was the case before but we recently made the decision to split off the ibc crate from the repository and to keep a copy of the subset the relayer needs in the ibc-delayer-types library. The reasoning behind this is that the relayer and the on-chain modules have very different requirements when it comes to no-std, object safety, etc. and keeping the dependency on them in the relayer was slowing down development of both the modules and the relayer. While the two set of types are currently  identical, we expect those to diverge in the coming weeks while we undo some of the modifications made solely for the purpose of the on-chain modules.
