### ISSUE TITLE
Split `gm` out of the `hermes` repo

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2754]
## Summary

It would make sense for `gm` to be split out from the `hermes` repo and have it maintained by Cephalopod; this would be a more appropriate breakdown of responsibilities. 

## Acceptance Criteria

- [ ] Split the `gm` directory out into its own repo

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
Do Cephalopod even use gm themselves? If not, then we should keep maintaining it, but I don't mind splitting it off in its own repo.

**Comment by harveenSingh** [comment]
Yes they do and they are in the favour of splitting it off in it's own repo. I have started working on this.

**Comment by romac** [comment]
Great!
