### ISSUE TITLE
Implement chain method to query for IBC acknowledgement

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes#2763]
## Summary

The original relayer code base do not have simple way to query for IBC acknowledgement when given only channel ID, port ID, and sequence. This makes it difficult for the new relayer to make use of existing code to query for such IBC acknowledgement.

The code with closest functionality is the [`query_write_ack_events`](https://github.com/informalsystems/hermes/blob/2122813a0c816c52e8d3bd387bc6618956428434/crates/relayer/src/link/packet_events.rs#L117) function. However it returns `Vec<IbcEvent>`, instead of `Option<WriteAcknowledgement>`.

In the relayer v2, we will implement new chain methods that construct the IBC acknowledgement directly without calling into the original relayer code base. We will refer to the implementation of `query_write_ack_events`, but implement the query directly in the `relayer-cosmos` crate without calling the original function.

## Steps to implement

1. Define a `CanQueryWriteAck` trait that looks something like follows:

```rust
#[async_trait]
pub trait CanQueryWriteAck<Counterparty>: HasIbcEvents<Counterparty>
where
    Counterparty: HasIbcChainTypes<Self>,
{
    async fn query_write_ack_event(
        channel_id: &Self::ChannelId,
        port_id: &Self::PortId,
        counterparty_channel_id: &Counterparty::ChannelId,
        counterparty_port_id: &Counterparty::PortId,
        sequence: &Counterparty::Sequence,
    ) -> Result<Option<Self::WriteAcknowledgementEvent>, Self::Error>;
}
```

2. Add a `query_write_ack_event` method to `OfaIbcChain` with something like follows:

```rust
#[async_trait]
pub trait OfaIbcChain<Counterparty>: OfaBaseChain
where
    Counterparty: OfaChainTypes,
{
    ...

    
    async fn query_write_ack_event(
        channel_id: &Self::ChannelId,
        port_id: &Self::PortId,
        counterparty_channel_id: &Counterparty::ChannelId,
        counterparty_port_id: &Counterparty::PortId,
        sequence: &Counterparty::Sequence,
    ) -> Result<Option<Self::WriteAcknowledgementEvent>, Self::Error>;
}
```

Stub the method with `todo!()` in the trait implementation for `CosmosChainWrapper`.

3. Implement `CanQueryWriteAck` for `OfaChainWrapper`.

4. Implement `query_write_ack_event` for `CosmosChainWrapper` without calling into the original relayer construct.
This would require extracting the implementation code from [`query_txs`](https://github.com/informalsystems/hermes/blob/2122813a0c816c52e8d3bd387bc6618956428434/crates/relayer/src/chain/cosmos/query/tx.rs#L41-L71) and reimplement it inside `relayer-cosmos`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Where would it make sense to define the `CanQueryWriteAck` trait?

**Comment by soareschen** [comment]
I think you can define it in `crate::base::chain::traits::queries`. We can always move them easily later.

**Comment by seanchen1991** [comment]
Does there also need to be an accompanying `WriteAckQuerier` trait alongside the `CanQueryWriteAck` trait?

**Comment by soareschen** [comment]
We can define that later when needed, as we would be first implementing `CanQueryWriteAck` directly for `OfaChainWrapper`.
