### ISSUE TITLE
Error output when upgrading client with `hermes upgrade client`

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#2781]
## Summary of Bug

There is an issue with the `hermes upgrade client` which seems to be related to the `Any` types.

Error output:

```
ERROR failed while trying to upgrade client id 07-tendermint-0 for chain ibc-0: failed while fetching from
chain the upgraded client state: conversion from a protobuf `Any` into a domain type failed: conversion
from a protobuf `Any` into a domain type failed:
error converting message type into domain type: the client state was not found
```

## Version

`master` branch 28.10.22, `hermes 1.0.0+3aba0ff27`

## Steps to Reproduce

Follow the guide to upgrade the chain, https://hermes.informal.systems/commands/upgrade/test.html.
Note that the command at step `2.` should actually be: `hermes tx upgrade-chain --reference-chain ibc-0 --host-chain ibc-1 --host-client 07-tendermint-0 --amount 10000000 --height-offset 60`

## Acceptance Criteria

- [ ] `upgrade client` works as expected
- [ ] https://github.com/informalsystems/hermes/issues/2312

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
just tried it with the latest master and it worked

```
SUCCESS [
    UpdateClient(
        UpdateClient {
            common: Attributes {
                client_id: ClientId(
                    "07-tendermint-0",
                ),
                client_type: Tendermint,
                consensus_height: Height {
                    revision: 0,
                    height: 80,
                },
            },
            header: Some(
                 Header {...},
            ),
        },
    ),
    UpgradeClient(
        UpgradeClient(
            Attributes {
                client_id: ClientId(
                    "07-tendermint-0",
                ),
                client_type: Tendermint,
                consensus_height: Height {
                    revision: 0,
                    height: 81,
                },
            },
        ),
    ),
]
```

**Comment by ljoss17** [comment]
It seems that this error is triggered when calling `hermes upgrade client --host-chain ibc-1 --client 07-tendermint-0 --upgrade-height <UPGRADE_HEIGHT>` with the incorrect `UPGRADE_HEIGHT`.
Otherwise, if the correct `UPGRADE_HEIGHT` is passed, everything works fine.
