### ISSUE TITLE
Add troubleshooting for scenarios where hermes cannot retrieve packet data from chain

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/hermes#2802]
## Summary
Under certain conditions hermes cannot retrieve the packet data from chain. As a first step these should be documented together with symptoms and fixes.

## Problem Definition
Triage is difficult for these scenarios and starting with a troubleshooting section would be valuable. 

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ljoss17** [comment]
## Hermes version

hermes 1.0.0+ed4dd8c8

## Issue

The command `hermes tx packet-ack` doesn’t seem to be able to get the events of the unreceived acknowledgments

## Attachments

<img width="1325" alt="likecoin_issue" src="https://user-images.githubusercontent.com/43531661/199460520-f872541a-ce0c-48a2-9fa8-861d8b7c5c56.png">
