### ISSUE TITLE
Move more default implementations to ChainEndpoint

### ISSUE THREAD

**Issue by kevinji** [informalsystems/hermes#2806]
## Summary

Move default implementations of `init_event_monitor`, `id`, `get_key`, and `add_key` from CosmosSdkChain to ChainEndpoint.

## Problem Definition

The implementations in CosmosSdkChain are generalizable, so moving them to ChainEndpoint reduces the amount of boilerplate for other chains.

## Proposal

See the summary.

## Acceptance Criteria

The functions are moved over to ChainEndpoint.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thanks for documenting this issue and opening a PR for it! The requested change seems straightforward. One of us will look into it in more detail and review your PR.
