### ISSUE TITLE
Test against Gaia v8.0.0-rc in CI

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2820]
## Acceptance Criteria

- [ ] `gaia` v8.0.0-rc is tested against in our CI pipeline 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Blocked on https://github.com/informalsystems/cosmos.nix/pull/108
