### ISSUE TITLE
CLI or script for event extraction debugging

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/hermes#2869]
## Summary
cc @romac
We currently use very rough tools to triage issues that involve packet data extraction. In the most recent example, on the ICS incentivized testnet, we needed to understand the cause of packets being stuck due to hermes not finding the packet data.

## Proposal

It would be very nice to have a CLI or script that:
- takes an RPC endpoint, a packet query and maybe a height
- retrieves the IBC events that match the query, maybe from the block results at the exact height
- displays the event attributes in a human readable form

Ideally this should not use hermes code but rather the RPC endpoints directly. But it could, at least initially, be part of the hermes repo (maybe in tools).

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
I have pretty much exactly this in a branch, will add support for the height and open a PR.
