### ISSUE TITLE
Default to 2/3 instead of 1/3 for IBC client security parameters

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#2876]
## Summary

Replace the 1/3 default with a 2/3 default.

Context: see the recommendation following the work by Tendermint team here: https://github.com/tendermint/tendermint/pull/9420

## Acceptance Criteria

 - [x] replace default trust threshold from 1/3 to 2/3 for IBC client security params
 - [ ] test relaying in a multi-network testate setup and confirm no impact is observed when validator sets continuously overlap
     - we should see no changes in the frequency of client updates or in the cost of client update messages
     - note: we already did some interesting tests in production with 1/1 trust threshold, refer to https://github.com/informalsystems/hermes/pull/1058

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by crodriguezvega** [comment]
@adizere Since the trust threshold is [configurable](https://github.com/informalsystems/hermes/blob/master/config.toml#L241), will there be some kind of validation to check that the threshold is >= 2/3? Otherwise an operator might choose to use a lower threshold anyway...

**Comment by adizere** [comment]
> @adizere Since the trust threshold is [configurable](https://github.com/informalsystems/hermes/blob/master/config.toml#L241), will there be some kind of validation to check that the threshold is >= 2/3? Otherwise an operator might choose to use a lower threshold anyway...

The value is already validated to be `> 0 and <=1`, that is, any value chose by an operator with Hermes must be a valid fraction larger than 0 and smaller than 1. But we don't plan to perform validation that it _should always be >= 2/3_. I think it's reasonable to allow operators to select different other values, eg 1/3 if they wish so. Do you see concerns with this?

**Comment by romac** [comment]
We currently [only relay on clients](https://github.com/informalsystems/hermes/blob/2960effefdf3cf0b715215b1e19263d521d8a0f7/crates/relayer/src/supervisor/client_state_filter.rs#L182) with a trust threshold `>= 1/3` and `<= 2/3`. Should we relax the upper bound to `1/1`?

**Comment by adizere** [comment]
> Should we relax the upper bound to `1/1`?

Not sure why we'd need that in the context of this issues. But I don't see problems with this change either!

**Comment by romac** [comment]
Otherwise we would only be allowing clients with a trust threshold of exactly 2/3. Which might be fine, but I seem to remember some previous discussion where we were thinking that we could allow clients with higher trust thresholds as well (though that was back when we were enforcing a trust threshold of 1/3 rather than 2/3).

**Comment by romac** [comment]
@ancazamfir What do you think?

**Comment by ancazamfir** [comment]
> @ancazamfir What do you think?

I think we should keep the `>=1/3` for now and change default to `2/3`. If someone wants `<1/3` they can create the client through other means. So maybe at some point we can allow that with a big warning.

**Comment by romac** [comment]
Agreed. I was asking about the upper bound, should we relax it to 1/1?

**Comment by ancazamfir** [comment]
> Agreed. I was asking about the upper bound, should we relax it to 1/1?

sorry i missed the question completely.  I don't see a reason to change the upper bound.
