### ISSUE TITLE
Acknowledgment issue

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#2920]
## Summary of Bug

The relayer has two issues:
* It is not sending acknowledgment messages when transferring tokens
* It is not sending acknowledgments with the correct height

## Version

Commit : 639338e0ecbaac437f0b46a21a19542c87712052

## Steps to Reproduce

Discovered with the MockChain implementation, since the current transfer test for the relayer 1.5 does not check the received acknowledgements but checks the chains balance.

## Acceptance Criteria

* An acknowledgment is sent when transferring tokens
* The correct height is used to relay acknowledgments

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Let's perhaps not mention relayer 1.5 in issues since this might be confusing as we haven't released it yet. Tagging with `relayer-next` should be enough.

**Comment by ljoss17** [comment]
Ok, I'll update the issues/PR

**Comment by soareschen** [comment]
Closed by https://github.com/informalsystems/hermes/pull/2921.
