### ISSUE TITLE
Support the IBC-go team with integrating Hermes into ibctest framework

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#2961]
## Problem statement

The IBC-go team kindly asked us if we would be able to dedicate some time in assisting them to integrate Hermes into ibctest framework. I think we should help them.

The scope of the work for our team includes as follows:

- followup on PRs that IBC-go team opens in ibctest, I think @chatton will shoulder most of the work
- provide synchronous assistance in case Hermes CLIs are unclear
- provide PR review, suggestions, testing support
- optional: update Hermes documentation (maybe the [features page](https://hermes.informal.systems/advanced/features.html)?) to mention integration in ibctest

This issue is purely for tracking purposes. Likely we won't need to open a PR on the Hermes repo. All work will go in the ibctest repo.

```[tasklist]
### Tasks
- [x] https://github.com/strangelove-ventures/interchaintest/pull/396
- [x] Set up docker images that get built per Hermes tag
```

## References

- https://github.com/strangelove-ventures/ibctest

**Comment by seanchen1991** [comment]
Marking this issue as closed due to [this PR](https://github.com/strangelove-ventures/interchaintest/pull/396) getting merged.

**Comment by chatton** [comment]
The docker images should be able to be built using a workflow similar to [this one](https://github.com/cosmos/ibc-go/blob/6be595a66e891ec10dbc7afcf36dfc509c685da9/.github/workflows/release.yml#L35-L59)

**Comment by chatton** [comment]
Thank you @romac , it looks like these are already built and pushed on tags, this is all we needed!
