### ISSUE TITLE
Hermes listen command is broken

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/hermes#3070]
## Summary of Bug
Hermes listen command
```
hermes listen --chain ibc-0
```
 is broken (since cb0c16f1d85366ccb42c8c58eff371db92786f50), there are no events printed.

## Version
cb0c16f1d85366ccb42c8c58eff371db92786f50 and after

## Steps to Reproduce
Run `hermes listen` with a chain producing blocks.

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Follow-up: https://github.com/informalsystems/hermes/issues/3096
