### ISSUE TITLE
Light client "header from the future" with unsynchronized hermes clock 

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/hermes#3139]
## Summary of Bug
(thanks @ljoss17 @romac @josef-widder for the help with the investigation)
@ljoss17 reported a hermes operator seeing these errors:
```
Mar 04 11:24:16 stride hermes[3403174]: 2023-03-04T10:24:16.855322Z  WARN ThreadId(76) worker.batch{chain=osmosis-1}:supervisor.handle_batch{chain=osmosis-1}:supervisor.process_batch{chain=osmosis-1}:worker.packet.cmd{src_chain=osmosis-1 src_port=transfer src_channel=channel-204 dst_chain=evmos_9001-2}: task encountered ignorable error: link error: failed during a client operation: error raised while updating client on chain evmos_9001-2: failed building header with error: light client verification error for chain id osmosis-1: invalid light block: header from the future: header_time=2023-03-04T10:24:43.824950138Z now=2023-03-04T10:24:16.84190695Z
```
After debugging the issue it turns out the relayer has a delayed clock, delay that is higher than the client clock drift.

When hermes needs to update the client for B on A it calls the light client verification that performs this check:
```rust
if (header_from_B.time > now + clock_drift) {
  return Err(HeaderFromTheFuture)
}
```
(see original code [here]( https://github.com/informalsystems/tendermint-rs/blob/d550fdf485fbe75a0bed4fa16f39e181d562789b/light-client-verifier/src/predicates.rs#L119-L136))
Where `clock_drift = B.clock_drift + A.clock_drift + A.max_block_time`. In this case the checks fails.
Note: A similar check is done  in hermes later here https://github.com/informalsystems/hermes/blob/6452553d1bc11ab63695ceb93db2af39abc21d08/crates/relayer/src/foreign_client.rs#L971-L978.

## Version
all

## Steps to Reproduce
Run a relayer with unsynchronized clock, with negative drift.

## Acceptance Criteria
We have two options:
- [ ] ~~Make mandatory that hermes should sync the clock and clearly document it, OR~~
- [x] Make hermes work  with unsynchronized clock. (fixed in #3224)

In addition:
- [ ] Document and explain why the final client "clock_drift" is derived from the reference and target chain clock_drifts, and the target chain max_block_time.

____

## For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by josef-widder** [comment]
I think it is important to note that while the system clock need not be synchronized, there still is the requirement that the times in the blocks/headers of the two chains need to be roughly synchronized.

**Comment by ancazamfir** [comment]
> I think it is important to note that while the system clock need not be synchronized, there still is the requirement that the times in the blocks/headers of the two chains need to be roughly synchronized.

True. The requirement is encoded in hermes but the documentation lacks and needs to improve.

**Comment by seanchen1991** [comment]
Is this issue able to be closed at this point?

**Comment by romac** [comment]
> > I think it is important to note that while the system clock need not be synchronized, there still is the requirement that the times in the blocks/headers of the two chains need to be roughly synchronized.
> 
> 
> 
> True. The requirement is encoded in hermes but the documentation lacks and needs to improve.

Let's document this somewhere in the guide and then we can close this, as we are not relying on the system time anymore.
