### ISSUE TITLE
Add health check to ensure chains are configured with the proper chain id

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3176]
## Summary

Add a health check which fetches the chain moniker from the `/genesis` endpoint and checks it against the configured chain id. Report an error otherwise.

## Problem Definition

See #3166 for background.

## Proposal

See summary.

## Acceptance Criteria

Hermes raises a warning/error when a chain is not configured properly, ie. its configured chain id does not match the one found in genesis.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Closed as we actually already check that the node's network ID matches the configured chain ID.
