### ISSUE TITLE
Remove dependency on `"message"` events

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#3190]
## Summary

Hermes [currently uses](https://github.com/informalsystems/hermes/blob/a285c015c604819b213c1582d901e5ef140d3f47/crates/relayer/src/event/monitor.rs#L147-L165) events of type `"message"`, which are SDK-specific. In my current understanding, since they are not technically IBC-specific, hermes should not rely on them to relay datagrams.

## Problem Definition

ibc-rs is now forced to emit these events too for hermes to be able to relay messages coming from an ibc-rs chain.

Related: https://github.com/cosmos/ibc-rs/issues/563

## Acceptance Criteria

ibc-rs doesn't need to emit these events anymore for `hermes` to successfully relay datagrams.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Related #2809
