### ISSUE TITLE
Support Interchain Security

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3198]
## Background

This issue tracks the work performed by the Hermes team that supports Interchain Security. 

```[tasklist]
## Q2 Tasks
- [ ] #3125 
- [ ] https://github.com/informalsystems/hermes/issues/2772
```
```[tasklist]
## Q3 Tasks
- [ ] #3175 
- [ ] #3387
```
____

#### For Admin Use

- [ ] `tracking` or `okr` label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by adizere** [comment]
seems like this was mostly limited to q2+q3 2023 and it's safe to close now

please reopen if that's not the case
