### ISSUE TITLE
Add `memo` field option to `hermes tx ft-transfer`

### ISSUE THREAD

**Issue by plafer** [informalsystems/hermes#3201]
## Summary

In ibc-rs we will soon add support for token transfer's memo field (https://github.com/cosmos/ibc-rs/issues/559). I would like to use `hermes` to test that feature in our integration tests, which would require this new field in the cli.

For reference, [here](https://github.com/cosmos/ibc-go/blob/9fbeb1c3e8d699ee51f49e157f51ebc5cd173571/proto/ibc/applications/transfer/v2/packet.proto#L19-L20) is the field in the packet data struct.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Hermes v1.4.0, which was just released, did add a `--memo` argument to `tx ft-transfer`: https://github.com/informalsystems/hermes/blob/daad02843a091bbdb3dd608e5f4ce790895c8845/crates/relayer-cli/src/commands/tx/transfer.rs#L116-L121 :)
