### ISSUE TITLE
Add channel upgrade init and try `tx` commands

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3237]
## Summary

As part of the work of implementing channel upgradability in Hermes, we'll need to add `hermes tx chan-upgrade-init` and `hermes tx chan-upgrade-try` CLI commands, similar to the `hermes tx chan-open-*` family of commands.

Part of this work also includes defining the message types needed in order for these commands to work.

**Comment by ljoss17** [comment]
`init` has not been implemented as it requires a governance proposal.
`try` Done by https://github.com/informalsystems/hermes/pull/3228
