### ISSUE TITLE
Add integration test for channel upgrades

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3244]
Track issues linked to channel upgradability tests.

- `ChannelUpgradeInit`: https://github.com/informalsystems/hermes/issues/3246
- `ChanUpgradeTry`: https://github.com/informalsystems/hermes/issues/3254
- `ChanUpgradeAck`: https://github.com/informalsystems/hermes/issues/3255
- Complete handshake: https://github.com/informalsystems/hermes/issues/3256

**Comment by seanchen1991** [comment]
Let's track these issues in the higher-level tracking issue 🙂
