### ISSUE TITLE
Introduce Hermes Band Protocol

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3300]
# Background

[This](https://github.com/bandprotocol/hermes) fork of Hermes implements the [Band Protocol](https://www.bandprotocol.com/): this introduces delaying a packet by X seconds. It would be nice to be able to configure this per channel for oracle channels.

**Comment by romac** [comment]
Seems like a duplicate of https://github.com/informalsystems/hermes/issues/3298, no?

**Comment by seanchen1991** [comment]
Yep, didn't see that Luca already opened an issue for this.
