### ISSUE TITLE
Thread count overflow

### ISSUE THREAD

**Issue by metodi96** [informalsystems/hermes#3324]
## Summary of Bug

A running Hermes relaying between two test networks (nolus-rila and osmo-test-4) encountered a "thread count overflow" error. 

Relevant background:
Nolus is a money market appchain heavily relying on IBC and Interchain Accounts. Each borrow position on Nolus
is a separate smart contract instance that registers an Interchain Account on a host network such as Osmosis.
For this reason, there are multiple separate ICA channels all of which need to be scanned. This seems like it might be a bottleneck for Hermes given the fact that the number of ICA channels rises with the number of lease positions registered. 

## Version

hermes 1.4.1 (hash: `45b5c292bc62db5110e4b1d61661b3e56778c811`) 

## Steps to Reproduce

Error log: 
`thread '<unnamed>' panicked at 'Thread count overflowed the configured max count.
 Thread index = 4098, max threads = 4096.', /root/.cargo/registry/src/github.com-
1ecc6299db9ec823/sharded-slab-0.1.4/src/shard.rs:295:9
thread '<unnamed>' panicked at 'Thread count overflowed the configured max count.
 Thread index = 4096, max threads = 4096.', /root/.cargo/registry/src/github.com-
1ecc6299db9ec823/sharded-slab-0.1.4/src/shard.rs:295:9
thread '<unnamed>' panicked at 'Thread count overflowed the configured max count.
 Thread index = 4097, max threads = 4096.', /root/.cargo/registry/src/github.com-
1ecc6299db9ec823/sharded-slab-0.1.4/src/shard.rs:295:9`

This error appeared while actively relaying between the Nolus Rila testnet (nolus-rila) and the Osmosis testnet (osmo-test-4). After restarting, the error was not present for a day after which it reappeared. It is difficult to reproduce this error.

## Acceptance Criteria

Finding the exact root cause of the error and specifying means to prevent it more reliably.
A dirty temporary solution would be to simply deny relaying on a list of specified channels using the `packet_filter` property in the configuration.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
As a sanity check for us, can you please try building and running Hermes from this branch, which disables the scanning when both `mode.clients.enabled = false` and `mode.connections.enabled = false`, since we do not need to spawn a worker per client and per connection in that case: https://github.com/informalsystems/hermes/compare/romac/scan-mode

If only a subset (<4k) of all ICA channels are active, it should help with the error you are seeing.

We are looking for a better and more long-term solution, will keep you posted!
