### ISSUE TITLE
Optimize Hermes' Performance

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3333]
## Background

This issue tracks the work revolving around improving Hermes' performance. 

```[tasklist]
- [ ] #3331 
- [ ] #3330 
- [ ] #3332 
```

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by romac** [comment]
Done 🎉
