### ISSUE TITLE
Remove idle workers

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#3385]
## Proposal

The packet worker should detect when it's been idle for too long and should abort its tasks.
In addition, some worker tasks are aborted after some conditions are met, but the workers are still kept in the `WorkerMap`. The idle workers should be removed from the `WorkerMap`.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Closed by #3365
