### ISSUE TITLE
Trigger packet processing manually through an endpoint

### ISSUE THREAD

**Issue by nik-suri** [informalsystems/hermes#3398]
## Summary

Enable users to manually specify packets to be clear on demand by `{channel-id}/{sequence_number}`.

## Problem Definition

There is a command `hermes clear packets`, but the intention behind this command seems to be that it should be run while the relayer process is not running. It would be helpful to manually instruct the running relayer process to clear packets on demand. While I believe that hermes is eventually consistent, clearing packets on demand can be helpful in situations when one needs to urgently test a flow, or users are complaining about long wait times - it seems that sometimes packets sit around for a while before being relayed.

## Proposal

I imagine the most straightforward way to implement this could be through an http endpoint. We could have 3 endpoints:
1. `/clear-packets` - to clear all packets from all IBC channels being monitored
2. `/clear-packets/{channel-id}` - to clear all packets from a given IBC channel
3. `/clear-packets/{channel-id}/{sequence_number}` - to clear a single specific packet.

## Acceptance Criteria

Functionality is implemented, whether through an http endpoint or not, that allows the relayer operator to clear packets manually on demand.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Can you give this branch a try and see if it works for you? https://github.com/informalsystems/hermes/pull/3401

**Comment by romac** [comment]
@nik-suri Can you please give this branch a try and see if it works for you? https://github.com/informalsystems/hermes/pull/3401
