### ISSUE TITLE
Docker image miss CA certificates for HTTPS RPC

### ISSUE THREAD

**Issue by mikentk** [informalsystems/hermes#3423]
## Summary of Bug
When using latest docker image, I get a CA error while trying to use HTTPS RPC endpoint
Following error is found in container log:
```
INFO ThreadId(01) running Hermes v1.5.1+6583d69
thread 'main' panicked at 'no CA certificates found', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.22.1/src/connector.rs:45:13
```
similar issue is solved [here](https://github.com/awslabs/aws-sdk-rust/discussions/434)

## Version
v.1.5.1 docker image

## Steps to Reproduce
Use HTTPS RPS endpoint in the relayer config

## Acceptance Criteria
HTTPS endpoint should work
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Thanks for the report! We'll add the required package and push the updated images tomorrow.
