### ISSUE TITLE
hermes v1.6.0: "Chain 'elgafar-1' has no minimum gas price value configured for denomination 'ustars'.

### ISSUE THREAD

**Issue by taitruong** [informalsystems/hermes#3597]
I get this warning on all chains, though I have configured it all:

```toml
default_gas = 40000
max_gas = 50000
gas_price = { price = 0.04, denom = 'ustars' }
gas_multiplier = 1.3
```

I tried also setting `min_gas`, but this doesn't exist in config, since I get this error:

```sh
The Hermes configuration file at path 'XYZ/config.toml' is invalid, reason: parse error: unknown field `min_gas`, expected one of `id`, `type`, `rpc_addr`, `grpc_addr`, `event_source`, `rpc_timeout`, `trusted_node`, `account_prefix`, `key_name`, `key_store_type`, `key_store_folder`, `store_prefix`, `default_gas`, `max_gas`, `genesis_restart`, `gas_adjustment`, `gas_multiplier`, `fee_granter`, `max_msg_num`, `max_tx_size`, `max_grpc_decoding_size`, `clock_drift`, `max_block_time`, `trusting_period`, `ccv_consumer_chain`, `memo_prefix`, `sequential_batch_tx`, `proof_specs`, `trust_threshold`, `gas_price`, `packet_filter`, `address_type`, `extension_options` for key `chains` at line 344 column 1
```

Error in code: https://github.com/informalsystems/hermes/blob/b7377772a3c9611cff25c5d8cf7ed9a5a26cf992/crates/relayer/src/chain/cosmos.rs#L2318-L2350

**Comment by romac** [comment]
The error is not very clear, but what it means is that the full node does not have an entry for `ustars` in its `min-gas-prices` setting, which is configured [here](https://github.com/cosmos/cosmos-sdk/blob/4963592e4064f1f9965a0cc6a7e9164db098ecc0/tools/confix/data/v0.47-app.toml#L11).

We'll improve the error message, to make this clearer!

Closing this, but feel free to re-open the issue if needed.
