### ISSUE TITLE
Ability to specify Tendermint CompatMode in chain config in `config.toml`

### ISSUE THREAD

**Issue by rootulp** [informalsystems/hermes#3623]
## Summary

Add the ability to explicitly set the Tendermint CompatMode in chain config in `config.toml`.

## Problem Definition

Celestia currently uses Tendermint v0.34.x but it has overridden the `version` field of the abci_info endpoint to return the application version (i.e. `v1.0.0-rc14`) and not the Tendermint version. See https://github.com/celestiaorg/celestia-core/issues/1035 and https://github.com/celestiaorg/celestia-core/pull/1036 for more details. 

As a result, of the code [here](https://github.com/informalsystems/hermes/blob/1c1cf02988db67507de7d484e1a7f317fe494d6c/crates/relayer/src/chain/cosmos.rs#L877-L880) and [here](https://github.com/informalsystems/hermes/blob/1c1cf02988db67507de7d484e1a7f317fe494d6c/crates/relayer-cli/src/commands/listen.rs#L179-L182), Hermes falls back to Tendermint compat mode v0.37 which breaks for celestia-app. More context on how this breaks in https://github.com/informalsystems/hermes/issues/3620.

## Proposal

Add the ability to explicitly set the Tendermint CompatMode in chain config in `config.toml`. If a chain doesn't specify it in chain config, then I think the current mechanism should be used where it is fetched from abci_info and falls back to v0.37.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Thanks for the suggestion! We'll get to this after the v1.7 release.

**Comment by romac** [comment]
Blocked until https://github.com/informalsystems/tendermint-rs/pull/1367 is released.
