### ISSUE TITLE
docs.rs builds are broken

### ISSUE THREAD

**Issue by hdevalence** [informalsystems/hermes#3624]
## Summary of Bug

The docs.rs build is broken, preventing docs from appearing on docs.rs: https://docs.rs/crate/ibc-relayer/0.25.0/builds/864826 

## Acceptance Criteria

docs.rs builds work.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Looks like we need to release a [0.25.1](https://crates.io/crates/ibc-relayer-types) patch like we did for `ibc-relayer-types`

**Comment by romac** [comment]
Fixed: https://docs.rs/ibc-relayer/0.25.1/ibc_relayer/
