### ISSUE TITLE
Hermes could accept mnemonics on the command line or via stdin

### ISSUE THREAD

**Issue by hdevalence** [informalsystems/hermes#3625]
## Summary / Proposal

The `keys add` subcommand only accepts a `--mnemonic-file` argument. This is annoying during development or when making test setups, because it means managing files. It would be more convenient to accept a mnemonic on the command line or via stdin.

## Acceptance Criteria

Hermes could add a flag like
`hermes keys add --mnemonic "SEED PHRASE"` to accept a mnemonic on the command line.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
I'd rather not give users a way to leak their seed phrase (eg. in their shell history or elsewhere) by letting them specify it on the command line, if that makes sense?

You can actually pass the mnemonic via stdin by specifying `--mnemonic-file /dev/stdin`, eg.

```
echo "$SEED_PHRASE" | hermes keys add --chain my-chain --mnemonic-file /dev/stdin
```

I am happy to discuss further and perhaps reconsider my position if the latter does not work for you, let me know!

**Comment by hdevalence** [comment]
Honestly, just mentioning that in the cli docs rendered with --help would be sufficient, I think, it didn't occur to me!
