### ISSUE TITLE
Update ibc-relayer and ibc crates to resolve cargo audit violations in dependencies

### ISSUE THREAD

**Issue by jkilpatr** [informalsystems/hermes#3656]
Both https://crates.io/crates/ibc-relayer and  https://crates.io/crates/ibc contain cargo audit identified vulnerabilities in their dependency spec.

These issues have been resolved in the master branch of this repo, but no release has been pushed up containing these updates.

**Comment by romac** [comment]
We'll fix this once we release Hermes v1.8.
