### ISSUE TITLE
Clear packets by specifying a range of sequence numbers to clear

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3672]
## Summary

Add a `--packet-sequences=SEQS` flag to the `clear packets` CLI for clearing only the packets with the given sequence numbers on the specified chain and channel.

## Problem definition

See #3750

## Proposal

Add a `--packet-sequences` flag to the `clear packets` CLI.

This flag accepts a list of ranges of sequence numbers to clear (`--packet-sequences=SEQS`), with the following format (in [EBNF](https://en.wikipedia.org/wiki/Extended_Backus–Naur_form)):

```
SEQS        = list
list        = item { "," list }
item        = seq | range
range       = upper-range | lower-range | full-range
upper-range = seq ".."
lower-range = ".." seq
full-range  = seq ".." seq
seq         = integer
```

Ranges are bounded inclusively below and above. The range `start..end` contains all values with `start <= x <= end`. It is empty if `start > end`.

### Examples

| Value | Meaning |
|:----- |:------- |
| `1` | Clear a single packet with sequence `1` |
| `1,2,3` | Clear packets with sequence numbers `1`, `2`, and `3` |
| `..20` | Clear all packets with sequence numbers less than or equal to `20` |
| `10..` | Clear all packets with sequence numbers greater than or equal to `10` |
| `10..20` | Clear all packets with sequence numbers `10`, `11`, `12`, ..., `20` |
| `2,4..6,12,14..17,21,30..` | Clear packets with sequence numbers `2`, `4`, `5`, `6`,  |`12`, `14`, `15`, `16`, `17`, `21`, `30`, `31`, `32`, ...
| `30..,21,12,14..17,4..6,2` | Same as previous, the order in which the ranges are specified does not matter |

**Comment by sryps** [comment]
I was just about to create an issue for this, I'd like to upvote the value of this! :)
