### ISSUE TITLE
Change `clear_interval` setting to be defined per chain

### ISSUE THREAD

**Issue by sryps** [informalsystems/hermes#3691]
## Summary

I am proposing the `clear_interval` be set per chain in the `chain` config section of config.toml

## Problem Definition

When relaying between a chain with a 6 second block time and a chain with a 1 second block time the clear interval can happen either too often and hurt performance of the relaying or not very often which isn't good for health of the channel.

Example Noble<>DYDX
if clear_interval is set to default 100:
- Noble clears packets every ~10min
- DYDX clears packets every 100seconds

if clear_interval is set to 500:
-  Noble clears packets every ~50min
- DYDX clears packets every 8.3min

if clear_interval is set to 1000:
-  Noble clears packets every ~1.6hours
- DYDX clears packets every 16.6min

The clear_interval happens X times more often on one chain vs the other when block speeds vary.

Not sure it's possible, but I guess another solution would be to use an amount of time vs every X block..`clear_interval = 30min`

I feel it would be beneficial to set the clear_interval per chain so there's more granular control over the occurrence rate.

## Acceptance Criteria

`clear_interval` can be set for each chain in config.toml.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
@ljoss17 Let's do this but keep the top-level `clear_interval` for now, and override it with the per-chain `clear_interval` if present.
