### ISSUE TITLE
No `timeout_packet` send to controller chain after estimated gas is higher than max from host chain 

### ISSUE THREAD

**Issue by mmsqe** [informalsystems/hermes#3695]
## Summary of Bug

Hermes will not send timeout packet when estimated gas exceeds max gas, so the channel state can't get closed after timeout, while go relayer works as expected.

## Version
current [master](https://github.com/informalsystems/hermes/commit/9e1b91bc6dc724b6cd08a3830b6c28e403be207b) 

## Steps to Reproduce

1. register ica account
2. fund ica account
3. submit large txs to trigger the exceeds max gas error in relayer
4. wait for channel state get [closed](https://github.com/crypto-org-chain/cronos/blob/e7a8ea84cb51042e8f292add9a074d17e288d24f/integration_tests/test_ica.py#L91) after timeout

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by devashishdxt** [comment]
@romac Is someone working on this? If not, can you provide an approximate outline of changes required so that I can start working on this? This is a blocker for us.

**Comment by romac** [comment]
@ljoss17 Can you please take a look?

**Comment by mmsqe** [comment]
Sorry for the late reply, channel closed [correctly](https://github.com/crypto-org-chain/cronos/actions/runs/10054886822/job/27790362170) after `MsgChannelCloseConfirm`, seems we need to set smaller timeout to trigger `MsgTimeout` first.
