### ISSUE TITLE
Support dynamic fees for chains with fee market (EIP-1559)

### ISSUE THREAD

**Issue by ertemann** [informalsystems/hermes#3738]
## Summary

With Osmosis and other chains adopting the Skip Block SDK and EIP1559 the gas fees are now no longer stagnant. We have had 2 times already where our relayer stopped because the on-chain feel went above our configured amount.

We would love a feature that allows to make the fee dynamic based on the on-chain endpoint: [lcd.osmosis.zone/osmosis/txfees/v1beta1/cur_eip_base_fee](https://lcd.osmosis.zone/osmosis/txfees/v1beta1/cur_eip_base_fee)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ljoss17** [comment]
Hi @ertemann thanks for opening this issue. I have the following proposal as a solution which will need some investigation from our side:

## Proposal

Depending on what data Hermes has access there are two possible solutions:

1. Hermes is able to retrieve the `base_fee` when simulating the Tx
2. Hermes can query the `base_fee`

For both solutions, once the `base_fee` has been retrieved the behaviour would then be similar to what is being done for gas amount:

1. Try to retrieve the `base_fee`
  a. If it succeeds, use that value
  b. If it fails use a fallback value `default_gas_price`
2. Check that the `base_fee` is not higher than a configured `max_gas_price`
3. Relay Tx

**Comment by romac** [comment]
We are planning to implement proper support for dynamic gas price based on the upcoming EIP-1559 FeeMarket module provided by the Skip SDK.

Until then, for Osmosis one can use [this fork of Hermes](https://github.com/czarcas7ic/hermes/releases/tag/v1.7.4-osmo-5) by Osmosis which adapts the gas price dynamically based on the `osmosis/txfees/v1beta1/cur_eip_base_fee` endpoint.
