### ISSUE TITLE
feat: version parsing should not prevent relaying

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/hermes#3753]
i get
```
WARN ThreadId(01) health_check{chain=centauri-dev}: chain is not healthy: failed while parsing version info for chain centauri-dev:http://127.0.0.1:9090/; caused by: failed to find the SDK module dependency ('cosmos/cosmos-sdk') for application centauri:-: failed to find the SDK module dependency ('cosmos/cosmos-sdk') for application centauri:-
```

from :

https://github.com/informalsystems/hermes/blob/3ec02fec9f8732c877398be53680ffa5e6531026/crates/relayer/src/chain/cosmos/query.rs#L160

chain produces blocks and can issue TX to it (cosmwasm/balances).

why Hermes considers chain broken? I guess it should not?

**Comment by dzmitry-lahoda** [comment]
next observations:
- why channel openeded SUCCESS, and yet cannot relay because of version? 
- WARN, why not ERROR if cannot relay?

**Comment by romac** [comment]
Are you seeing any other errors after that or just this warning?

**Comment by dzmitry-lahoda** [comment]
No other errors. 
Packet sent success on source chain over open channel. 
But relayer never finds that packet.
No errors no other warnings.
Target chain version parsing is ok.

I found that version query has deps list empty, may because I build wirh mod=vendor.

**Comment by dzmitry-lahoda** [comment]
other thing to note, source of data is debug 

https://pkg.go.dev/runtime/debug

so if it it the case that build_deps emptyness in vendored build prevents relaying it may be not super.

**Comment by dzmitry-lahoda** [comment]
my latest state

```
bash-5.2$ ./result/bin/centaurid  version --long
build_deps: null
build_tags: ""
commit: 2fbea67cef8086dbc459fb7623c321fdf8641691-dirty
cosmos_sdk_version: ""
go: go version go1.21.5 linux/amd64
name: centaurid
server_name: centauri
version: v7.0.0

bash-5.2$ 
````

**Comment by dzmitry-lahoda** [comment]
```
  WARN ThreadId(21) health_check{chain=centauri-dev}: Health checkup for chain 'centauri-dev' failed"}
  WARN ThreadId(21) health_check{chain=centauri-dev}:     Reason: failed while parsing version info for chain centauri-dev:http://127.0.0.1:9090/; caused by: failed to find the SDK module dependency ('cosmos/cosmos-sdk') for application centauri:v7.0.0-2fbea67cef8086dbc459fb7623c321fdf8641691"}
 TRACE ThreadId(03) client::dispatch::Sender dropped"}
  WARN ThreadId(21) health_check{chain=centauri-dev}:     Some Hermes features may not work in this mode!"}
```

**Comment by dzmitry-lahoda** [comment]
striping flag is `--ldflags "-s" `
