### ISSUE TITLE
WARN Hermes health check failed Ibc-Go on UNI-6

### ISSUE THREAD

**Issue by StakeandRelax-Validator** [informalsystems/hermes#3831]
## Error
chain is not healthy: Hermes health check failed while verifying the application compatibility for chain uni-6:http://127.0.0.1:9090/; caused by: Ibc-Go module at version '0.1.1' does not meet compatibility requirements >=4.1.1, <9

## Version
v1.8.0+39036d1

## Why
It's getting the light-client ibc-go implementation of UNI-6 (and soon JUNO-1)

junod version --long | grep ibc-go
- github.com/cosmos/ibc-go/modules/light-clients/08-wasm@v0.1.1-0.20231213092633-b306e7a706e1
- github.com/cosmos/ibc-go/v7@v7.3.1

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
You can safely ignore the warning, but thanks for the report, we'll fix the version parsing code in the next release.
