### ISSUE TITLE
CLI `clear packets` fails due to `counterparty_channel_id` not found

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#3889]
## Summary of Bug

Packet clearing filter https://github.com/informalsystems/hermes/pull/3862 introduced a bug with the `clear packets` CLI. The command is likely to fail or clear packets for the incorrect channel since the reverse link uses the source channel and port IDs.

## Version

v1.8.1

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Fixed in Hermes v1.8.2

**Comment by adamewozniak** [comment]
Ty for this!
