### ISSUE TITLE
failed CreateClient: error raised while creating client for chain ciferb: failed when building client state:

### ISSUE THREAD

**Issue by cifer-ai** [informalsystems/hermes#3897]
We are doing Hermes create channel between cifer (chain a) and ciferb (chain b) and get this error.

Using command:
hermes create channel --a-chain cifer --b-chain ciferb --a-port transfer --b-port transfer --new-client-connection

Error:
2024-03-15T16:22:41.885046Z  INFO ThreadId(01) Creating new clients, new connection, and a new channel with order ORDER_UNORDERED
2024-03-15T16:22:42.127741Z ERROR ThreadId(01) [ciferb -> cifer:07-tendermint-0]  failed CreateClient: error raised while creating client for chain ciferb: failed when building client state: gRPC call failed with status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
ERROR error raised while creating client for chain ciferb: failed when building client state: gRPC call failed with status: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

We checked our rpc node status as shown in cosmos directory and found it working properly.
https://cosmos.directory/cifer

In this case, could you kindly advise troubleshoot method to fix this error while grpc functions properly as shown in directory

## Version
hermes version 1.0.0, ibc-rs version 1.0.0

## For Admin Use
- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Can you please share your Hermes config for that node?

**Comment by cifer-ai** [comment]
Yes sure, this is config.toml

[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'cifer'
rpc_addr = 'https://cif_node.cifer.ai/'
grpc_addr = 'http://34.128.114.243:26657'
websocket_addr = 'ws://0.0.0.0:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'alice'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.001, denom = 'stake' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''

[[chains]]
id = 'ciferb'
rpc_addr = 'https://cif_node.cifer.ai/'
grpc_addr = 'http://34.128.114.243:26657'
websocket_addr = 'ws://0.0.0.0:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'bob'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.001, denom = 'stake' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
type = "CosmosSdk"
id = "osmosis-1"
rpc_addr = "https://rpc-osmosis-ia.cosmosia.notional.ventures"
grpc_addr = "https://osmosis-grpc.lavenderfive.com/"
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = "10s"
account_prefix = "osmo"
key_name = "keyosmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = "5s"
max_block_time = "30s"
memo_prefix = ""

[[chains]]
type = "CosmosSdk"
id = "cosmoshub-4"
rpc_addr = "https://cosmos-rpc.staketab.org/"
grpc_addr = "https://cosmoshub-grpc.lavenderfive.com/"
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = "10s"
account_prefix = "cosmos"
key_name = "keyhub"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.025, denom = 'uatom' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = "5s"
max_block_time = "30s"
memo_prefix = ""

**Comment by romac** [comment]
Ar a first glance, the `grpc_addr` for cifr looks more like a RPC address instead of a gRPC one, as evidenced by the response I get when I open it in a web browser. You need to specify the address of a gRPC server instead.
Also, Hermes 1.0.0 is way outdated by now, the latest version is 1.8.2. Please give it another try with the fixed gRPC address and the latest Hermes and report back. Note that the config file has changed a bit in the meantime so you might need to either adapt it by hand or generate a new one with the `hermes config auto` command. See the guide at http://hermes.informal.systems for more info.

**Comment by cifer-ai** [comment]
Thank you for your advice.

1. We install Hermes 1.8.2
2. At first we use command hermes config auto and it cannot write cifer chain config, so we add it manually.
3. We have sufficient funds in all 3 accounts (keys for cosmoshub, osmosis, cifer)
4. Then we work on gRPC and websocket on Gaia and set them up in the following ips and ports:

gRPC : http://34.128.114.243:9090
websocket : wss://34.128.114.243:26658

---

This is our new config.

[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
type = "CosmosSdk"
id = "cifer"
rpc_addr = "https://cif_node.cifer.ai"
grpc_addr = "http://34.128.114.243:9090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cifer"
key_name = "key-cifer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 990000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"
url = "wss://34.128.114.243:26658"
batch_delay = "500ms"

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "uatom"

[chains.packet_filter]
policy = "allow"
list = [
    [
    "transfer",
    "channel-0",
],
    [
    "transfer",
    "channel-0",
],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = true
multiplier = 1.5
max = 0.6

[chains.address_type]
derivation = "cosmos"

[[chains]]
type = "CosmosSdk"
id = "osmosis-1"
rpc_addr = "https://osmosis-rpc.onivalidator.com"
grpc_addr = "https://grpc.osmosis.zone:443"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "osmo"
key_name = "key-osmosis"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 990000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"
url = "wss://rpc.osmosis.zone/websocket"
batch_delay = "500ms"

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "uosmo"

[chains.packet_filter]
policy = "allow"
list = [
    [
    "transfer",
    "channel-0",
],
    [
    "transfer",
    "channel-0",
],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = true
multiplier = 1.5
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[[chains]]
type = "CosmosSdk"
id = "cosmoshub-4"
rpc_addr = "https://cosmos-rpc.onivalidator.com"
grpc_addr = "https://cosmoshub-grpc.lavenderfive.com"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cosmos"
key_name = "key-cosmos"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 990000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"
url = "wss://rpc-cosmoshub.ecostake.com/websocket"
batch_delay = "500ms"

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "uatom"

[chains.packet_filter]
policy = "allow"
list = [
    [
    "transfer",
    "channel-0",
],
    [
    "transfer",
    "channel-141",
],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = false
multiplier = 1.5
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[tracing_server]
enabled = false
port = 5555

---

We did hermes create client, connection and channel for osmosis-cosmoshub and it success.
While we create client for cifer-cosmoshub, we get this error:

ERROR foreign client error: error raised while creating client for chain cifer: failed when building client state: error in underlying transport when making gRPC call: transport error

---

We try install and run Gaia, Hermes on our server and change RPC, gRPC, websocket to be on localhost instead.

RPC : http://127.0.0.1: 26557
gRPC : http://127.0.0.1: 9090
websocket : wss://127.0.0.1:26658

Then we run Hermes create client command again, and get this error:

ERROR foreign client error: error raised while creating client for chain cifer: failed sending message to dst chain : gRPC call `query_account` failed with status: status: Unknown, message: "codespace sdk code 26: invalid height: GaiaApp is not ready; please wait for first block", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

I suspect maybe we didn't setup gRPC right, or did it ask for gRPC client.

In this case, could you kindly advise troubleshoot method to fix this error, or how to work on gRPC correctly.

**Comment by romac** [comment]
It looks the gRPC server was indeed not setup properly, ie. `transport error` means that Hermes cannot connect to it.

However, when I run this command from my laptop, it seems like the gRPC server is accessible:

```
❯ grpcurl -plaintext 34.128.114.243:9090 list
cosmos.auth.v1beta1.Query
cosmos.authz.v1beta1.Query
cosmos.autocli.v1.Query
cosmos.bank.v1beta1.Query
cosmos.base.node.v1beta1.Service
(etc...)
```

I am not sure how to further help with debugging this. You might want to look at the logs of the node/gRPC server and see if anything stands out.

**Comment by cifer-ai** [comment]
We try running Hermes on our server and set grpc address as local ip and port and it works now.
