### ISSUE TITLE
gRPC call fails with `GaiaApp is not ready; please wait for first block`

### ISSUE THREAD

**Issue by cifer-ai** [informalsystems/hermes#3912]
## Summary of Bug

When we try creating client using this command:
`$ hermes create client --host-chain cifer --reference-chain cosmoshub-4`

We get this error:
`ERROR foreign client error: error raised while creating client for chain cifer: failed sending message to dst chain : gRPC call `query_account` failed with status: status: Unknown, message: "codespace sdk code 26: invalid height: GaiaApp is not ready; please wait for first block", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }`

Then we try creating client using this command:
`$ hermes create client --host-chain cosmoshub-4 --reference-chain cifer`

We get this error:
`ERROR foreign client error: error raised while creating client for chain cifer: failed when building client state: gRPC call `query_staking_params` failed with status: status: Unknown, message: "codespace sdk code 26: invalid height: GaiaApp is not ready; please wait for first block", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }`

## Version

hermes version 1.8.2, ibc-rs version 1.0.0

## Steps to Reproduce

1. To check if there are any error on Hermes, we create client, connection and channel for osmosis-cosmoshub and it success. So we suspect the error may be because of Cifer chain config or some setup we are missing.

2. Our config for Cifer chain:

```
[[chains]]
type = "CosmosSdk"
id = "cifer"
rpc_addr = "https://cif_node.cifer.ai:443"
grpc_addr = "http://34.128.114.243:9090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cosmos"  
key_name = "key-cifer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 990000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"  
url = "ws://34.128.114.243:26658"
batch_delay = "500ms"
[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.025
denom = "uatom"

[chains.packet_filter]
policy = "allow"
list = [
    [
    "transfer",
    "channel-0",
],
    [
    "transfer",
    "channel-0",
],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = true
multiplier = 1.5
max = 0.6
     
[chains.address_type]
derivation = "cosmos"
```

3. We perform Hermes health check
`$ hermes health-check`

Then we get these warning for Cifer chain:
```
2024-03-22T12:37:26.849920Z  WARN ThreadId(12) health_check{chain=cifer}: health check failed for chain 'cifer'
2024-03-22T12:37:26.849994Z  WARN ThreadId(12) health_check{chain=cifer}: reason: gRPC call `get_syncing` failed with status: status: Unknown, message: "codespace sdk code 26: invalid height: GaiaApp is not ready; please wait for first block", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
2024-03-22T12:37:26.850010Z  WARN ThreadId(12) health_check{chain=cifer}: some Hermes features may not work in this mode!
2024-03-22T12:37:26.852822Z  WARN ThreadId(01) health_check{chain=cifer}: chain is not healthy
```

4. We check if our grpc works with this command:
`$ grpcurl -plaintext 34.128.114.243:9090 list`

and it show result:
```
cosmos.auth.v1beta1.Query
cosmos.authz.v1beta1.Query
cosmos.autocli.v1.Query
cosmos.bank.v1beta1.Query
cosmos.base.node.v1beta1.Service
cosmos.base.reflection.v1beta1.ReflectionService
cosmos.base.reflection.v2alpha1.ReflectionService
cosmos.base.tendermint.v1beta1.Service
cosmos.consensus.v1.Query
cosmos.distribution.v1beta1.Query
cosmos.evidence.v1beta1.Query
cosmos.feegrant.v1beta1.Query
cosmos.gov.v1.Query
cosmos.gov.v1beta1.Query
cosmos.mint.v1beta1.Query
cosmos.params.v1beta1.Query
cosmos.reflection.v1.ReflectionService
cosmos.slashing.v1beta1.Query
cosmos.staking.v1beta1.Query
cosmos.tx.v1beta1.Service
cosmos.upgrade.v1beta1.Query
gaia.globalfee.v1beta1.Query
grpc.reflection.v1alpha.ServerReflection
ibc.applications.interchain_accounts.host.v1.Query
ibc.applications.transfer.v1.Query
ibc.core.channel.v1.Query
ibc.core.client.v1.Query
ibc.core.connection.v1.Query
interchain_security.ccv.provider.v1.Query
packetforward.v1.Query
testpb.Query
```

5. To check if wallets have funds, we use this command:

`$ hermes keys balance --chain cosmoshub-4`
Output: balance for key key-cosmos: 24583 uatom

`$ hermes keys balance --chain osmosis-1`
Output: balance for key key-osmosis: 284037 uosmo

For Cifer chain, it shows error
`$ hermes keys balance --chain cifer`
Output: ERROR there was a problem querying the balance: gRPC call `query_balance` failed with status: status: Unknown, message: "codespace sdk code 26: invalid height: GaiaApp is not ready; please wait for first block", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

But if checking this wallet address on explorer, it will show its balance:
https://www.mintscan.io/cosmos/address/cosmos18a2m0xnpr5hkal4alx5ja534vvl3ckk6g4xgmx/

6. When we setup grpc we use Gaia, setup port in app.toml

## Acceptance Criteria

In this case, please provide troubleshoot instruction to fix this error.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cifer-ai** [comment]
As the error said "invalid height", we check our block status and it's already running as you can see it here:
https://cif_node.cifer.ai/status
```
{
"latest_block_hash":"1EEB7E3F7E5F347600D99FD4773D98830042006166720FEEFE320ADE5476658E",
"latest_app_hash":"B1B1C4F4E81B12959C35F64C515894D37718D7BD3A5A2AEFA3A7D4160D4C3833",
"latest_block_height":"501838",
"latest_block_time":"2024-03-25T15:25:11.526751523Z",
"earliest_block_hash":"5FE07CD7F5819B9BDDADA9CC2AE15235FE12322C1698A15F63DC10AC3363BDCB",
"earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
"earliest_block_height":"1",
"earliest_block_time":"2024-03-19T15:51:14.610398132Z",
"catching_up":false
},
```

So what can cause the error "invalid height" when our blockchain already has block height.

**Comment by romac** [comment]
This error is [raised by the SDK](https://github.com/cosmos/cosmos-sdk/blob/a82615bdf8057bb491539bc4fdd0143174842282/baseapp/abci.go#L1215-L1218) when the last block height in the store is zero, so it seems like there is something going wrong with the store. I don't believe Hermes can do anything about that since this error is not dependent on the queried height.

**Comment by cifer-ai** [comment]
Thank you for your advice. I have reach Cosmos SDK support for this issue and they said they are not sure how this is an sdk bug as the state machine is working as expected. Seems like something may be wrong with the hermes configuration.

This time we try something else, by changing our chain config in Cifer App, run our chain on local, and test it using localhost address:
rpc_addr = "http://0.0.0.0:26657"
grpc_addr = "http://0.0.0.0:9090"
websocket : "ws://0.0.0.0:26657/websocket"

And there's no previous error, but get this error instead:
`ERROR foreign client error: error raised while creating client for chain cifer-1: failed sending message to dst chain : gRPC call `query_account` failed with status: status: Unknown, message: "codespace sdk code 35: internal logic error: hrp does not match bech32 prefix: expected 'cosmos' got 'cife'", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "10328"} }`

Our registered human-readable parts for usage in Bech32 encoding is "cife" for Cifer mainnet as you can see it here:
https://github.com/satoshilabs/slips/blob/master/slip-0173.md

**Comment by romac** [comment]
Seems like Hermes is using the correct prefix then, but the app is expecting `cosmos`. What happens if you change the `account_prefix` in the Hermes config to something random, or to `cosmos`?

**Comment by cifer-ai** [comment]
At first we set hermes config as:
`account_prefix = "cife"`

Then we try changing it to:
`account_prefix = "cosmos"`

It still show the same error as above.

**Comment by romac** [comment]
Not sure what else Hermes can do, if the error is the same with both configs, to me that would point to an issue on the app side. I am not trying to pass the buck here, but I am not sure how to help more.

Is Cifer a standard Cosmos SDK app? Which version of the SDK are you using?

**Comment by cifer-ai** [comment]
Yes Cifer is a standard Cosmos SDK app, using Cosmos SDK v0.45.4

**Comment by cifer-ai** [comment]
This time we switch between host chain and reference chain:
`$ hermes create client --host-chain cosmoshub-4 --reference-chain cifer-1`
and it works.

---

Then we create connection:
`$ hermes create channel --order unordered --a-chain cosmoshub-4 --b-chain cifer-1 --a-port transfer --b-port transfer --new-client-connection`

We get this error:
`ERROR ThreadId(20) foreign_client.create{client=cosmoshub-4->cifer-1:07-tendermint-0}:send_messages_and_wait_commit{chain=cifer-1 tracking_id=create client}:send_tx_with_account_sequence_retry{chain=cifer-1 account.sequence=0}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "spendable balance 0uatom is smaller than 24751uatom: insufficient funds: insufficient funds [cosmos/cosmos-sdk@v0.50.1/x/auth/ante/fee.go:137] With gas wanted: '18446744073709551615' and gas used: '13476' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "2330"} }`

We check account for key-cifer
`$ hermes keys list --chain cifer-1`

And we get this address
`- key-cifer (cife18a2m0xnpr5hkal4alx5ja534vvl3ckk6t4gm9f)`

So we suspect that the previous error: 
`expected 'cosmos' got 'cife'`
Maybe Hermes is looking for the address of "cosmosxxxx..." account, but it found "cifexxxxxx..." account instead.

---

We delete the old key and create new key, and send some ATOM to the new "cosmos18a2m0xnpr5hkal4alx5ja534vvl3ckk6g4xgmx" account and we try create connection again.

This time we get this error:
`ERROR error raised while creating client for chain cifer-1: failed sending message to dst chain : gRPC call `query_account` failed with status: status: NotFound, message: "account cosmos18a2m0xnpr5hkal4alx5ja534vvl3ckk6g4xgmx not found", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "12131"} }`

As we search for this error, it means there is no balance in this wallet.
Which account cosmos18a2m0xnpr5hkal4alx5ja534vvl3ckk6g4xgmx already has ATOM as you can see it here:
https://www.mintscan.io/cosmos/address/cosmos18a2m0xnpr5hkal4alx5ja534vvl3ckk6g4xgmx/

Then we use this command to check balance for key-cifer:
`$ hermes keys balance --chain cifer-1`

And it turn out there is no balance:
`SUCCESS balance for key `key-cifer`: 0 uatom`

So we're not sure if
1. Wallet for Cifer key has to be the wallet on Cifer chain, which now support only CIF token so it can not read ATOM token.
2. Should we change account_prefix to ucif, create wallet "cifexxxxx...", add some CIF to wallet and try again.

**Comment by cifer-ai** [comment]
Problems fixed by stop Gaia which running in the background, and fix prefix on Cifer chain.
