### ISSUE TITLE
Token transferring problem: didnot receive token on destination wallet

### ISSUE THREAD

**Issue by cifer-ai** [informalsystems/hermes#3931]
## Summary of Bug

We did Hermes relayer and then transfer IBC tokens using this command:
`hermes tx ft-transfer --timeout-seconds 1000 --dst-chain osmosis-1 --src-chain cifer-1 --src-port transfer --src-channel channel-2 --amount 10 --denom ucif`

First time the transferring went well, as you can see in this tx
https://chainsco.pe/osmosis/tx/14654B85E8CEDD21D0B8645DCC40ABC1DABA843D2946FB41D9AEB3B76DE6A878

---

Then we have a few config on our chain: changing chain-id from "cifer" to "cifer-1"
But from the start, we have set chain-id config in Hermes config as "cifer-1"

Without any Hermes config changed, this time when we transfer cif tokens, the outbound was success (tokens on host chain were decreased), but there is no tokens received on the destination wallet.
The result after transferring show like this:
```
SUCCESS [
    IbcEventWithHeight {
        event: SendPacket(
            SendPacket {
                packet: Packet {
                    sequence: 8,
                    source_port: PortId(
                        "transfer",
                    ),
                    source_channel: ChannelId(
                        "channel-2",
                    ),
                    destination_port: PortId(
                        "transfer",
                    ),
                    destination_channel: ChannelId(
                        "channel-35741",
                    ),
                    data: [123, 34, 97, 109, 111, 117, 110, 116, 34, 58, 34, 49, 48, 34, 44, 34, 100, 101, 110, 111, 109, 34, 58, 34, 117, 99, 105, 102, 34, 44, 34, 114, 101, 99, 101, 105, 118, 101, 114, 34, 58, 34, 111, 115, 109, 111, 49, 108, 122, 117, 120, 50, 108, 119, 117, 56, 120, 55, 99, 103, 107, 52, 113, 119, 56, 114, 54, 104, 54, 106, 120, 103, 122, 110, 115, 52, 54, 53, 117, 99, 121, 101, 100, 53, 50, 34, 44, 34, 115, 101, 110, 100, 101, 114, 34, 58, 34, 99, 111, 115, 109, 111, 115, 49, 103, 117, 57, 97, 99, 108, 108, 110, 97, 109, 54, 112, 56, 50, 107, 121, 115, 118, 99, 57, 119, 112, 119, 56, 109, 104, 50, 121, 54, 115, 52, 118, 110, 55, 119, 122, 101, 117, 34, 125],
                    timeout_height: Never,
                    timeout_timestamp: Timestamp {
                        time: Some(
                            Time(
                                2024-04-05 10:44:38.14070815,
                            ),
                        ),
                    },
                },
            },
        ),
        height: Height {
            revision: 1,
            height: 753674,
        },
    },
]

```

Then we try sending osmo and atom, the result remain the same.

Meanwhile, when we test transferring atom token from cosmoshub to osmosis using this command
`hermes tx ft-transfer --timeout-seconds 1000 --dst-chain osmosis-1 --src-chain cosmoshub-4 --src-port transfer --src-channel channel-803 --amount 10 --denom uatom`

We get this error
`ERROR transfer error: failed while submitting the Transfer message to chain cosmoshub-4: failed tx: no confirmation`

But the tokens were successfully transferred and received, as you can see in this tx
https://chainsco.pe/osmosis/tx/0C447A46DA0B455357C1DEC11B61B30BCC91C4920CE2CA096623AB99C2D3353F

---

We ask Osmosis support and they address that it might be because we change our chain-id, so we need to create new client and submit gov proposal to update it and use with the current connection and channel.

But as we test by creating new client, connection, channel with this new chain-id "cifer-1" and test transferring tokens, the problem remain the same. So we are not sure if creating new client will solve this problem.

As we check Hermes config with `hermes health-check` it turn out all chains are healthy.

## Version
hermes 1.8.2+06dfbaf

## Acceptance Criteria

Please consider these errors if it's a bug or if we made any mistake, and please give us steps to troubleshoot this error to make the IBC transferring success.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
You indeed likely need to create a new client to reflect the change of chain id. The fact that it was previously set to a chain id different than the real one may also explain why you were having issues earlier.

You can safely ignore the `no confirmation` error, sometimes it takes longer than Hermes expects for the tx to show up on chain, and it will then emit this error when `tx_confirmation = true`. We should probably downgrade it to a warning.

**Comment by cifer-ai** [comment]
Got it, thank you.
