### ISSUE TITLE
Add support for multiple connection hops in `tx chan-open-init`

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3950]
### [`tx chan-open-init`](https://github.com/informalsystems/hermes/blob/master/crates/relayer-cli/src/commands/tx/channel.rs)

- [x] Add `--connection-hops=conn1,conn2,conn3` parameter to `tx chan-open-init`
- [x] Define `ConnectionHop` struct
- [x] Define `ConnectionHops` struct initially with single field `hops: Vec<ConnectionHop>`
- [x] Fetch alls connections and store them in `ConnectionHops`
  - [x] 1. Fetch destination connection (`--dst-connection`) on the destination
  - [x] 2. Fetch the client state for the client underlying that connection on the destination chain
  - [x] 3. Get the counterparty chain id from the client state
  - [x] 4. Do this for all connection hops, from last to first
- [x] Add `connection_hops: ConnectionHops` field to [`Channel` struct](https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/channel.rs?plain=1#L166)
- [x] Add support for connection hops to [`Channel::build_chan_open_init_and_send`](https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/channel.rs?plain=1#L875)
  - [x] Change `connection_id` field on struct [`Attributes`](https://github.com/informalsystems/hermes/blob/962cbd11e28659383dc997da63129e0d8d700835/crates/relayer-types/src/core/ics04_channel/events.rs#L35) to a `Vec<ConnectionId>`
  - [x] Parse `connection_id`s from `channel_open_init` event into `Attributes.connection_id`
- [x] Write unit tests for `tx chan-open-init` with `--connection-hops`
- [ ] Write integration test for single hop channel

```rust
struct ConnectionHop {
  pub connection: IdentifiedConnectionEnd,
  pub client_state: AnyClientState,
  pub reference_chain_id: ChainId,
}
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by joaotav** [comment]
Closed by 0ec88bd.
