### ISSUE TITLE
Add support for multiple connection hops in `tx chan-open-try`

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3987]
Part of: #3940

### [`tx chan-open-try`](https://github.com/informalsystems/hermes/blob/master/crates/relayer-cli/src/commands/tx/channel.rs#L169)
- [x] Replace call to `tx_chan_cmd!` macro with an inline function on [`TxChanOpenTryCmd`](https://github.com/informalsystems/hermes/blob/25f547595ff71a4910a68889c625ad7b66180de9/crates/relayer-cli/src/commands/tx/channel.rs#L237)
- [x] In the [`run()`](https://github.com/informalsystems/hermes/blob/25f547595ff71a4910a68889c625ad7b66180de9/crates/relayer-cli/src/commands/tx/channel.rs#L236) function for `TxChanOpenTryCmd`, build the reverse channel path, from `--dst-chain` to `--src-chain`, by leveraging information available on the existing `ChannelEnd` that was opened with `tx chan-open-init`
- [x] Add multihop support to [Channel::build_chan_open_try_and_send](https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/channel.rs#L1063)
  - [x] Add `build_multihop_chan_open_try()` method to struct `Channel` 
  - [x] Add `update_channel_path_clients()` method to struct `Channel`
    - [x] Add struct `MultihopProofHeights` to store the heights that are necessary when constructing multihop proofs.
  - [x] Add `build_multihop_proofs()` method to struct `Channel`

### Tests
- [ ] Write integration test for single hop channel
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by joaotav** [comment]
Closed by 81123d2.
