### ISSUE TITLE
Option to disable ICQ

### ISSUE THREAD

**Issue by hallazzang** [informalsystems/hermes#4040]
## Summary

I want to run both cosmos/relayer and hermes. I want cosmos/relayer to handle ICQ so I need an option to disable ICQ on hermes. Currently I don't see any options for that.

## Problem Definition

Running hermes standalone seems not working well ICQ, thus I'm running both relayers at the same time.
The problem is that both relayers trying to submit `MsgSubmitQueryResponse` causes account sequence mismatch error.

## Proposal

Have an option to disable ICQ.

## Acceptance Criteria

Same as above I guess.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
@hallazzang Would this work for you? https://github.com/informalsystems/hermes/issues/4041

If you could give a try and report back it would be a great help :)
