### ISSUE TITLE
 Add support for multiple connection hops in `tx chan-open-ack` 

### ISSUE THREAD

**Issue by joaotav** [informalsystems/hermes#4049]
Part of: #3940

### [`tx chan-open-ack`](https://github.com/informalsystems/hermes/blob/e5e55788c37c6d5d0785d9f78e19cd7a81b8aaab/crates/relayer-cli/src/commands/tx/channel.rs#L327)

- [x] Replace call to `tx_chan_cmd!` macro with an inline function on [`TxChanOpenAckCmd`](https://github.com/informalsystems/hermes/blob/e5e55788c37c6d5d0785d9f78e19cd7a81b8aaab/crates/relayer-cli/src/commands/tx/channel.rs#L327)
- [x] Add `build_multihop_chan_open_ack()` to method `build_chan_open_ack_and_send()` to enable the construction of `MsgChannelOpenAck` messages when multiple connection hops have been specified.
- [x] Modify `validated_expected_channel()` to support channel ends with multiple connection hops on the destination chain.

### Tests

- [x] Manual testing for single-hop channel handshake
- [x] Manual testing for multihop channel handshake with 2 connection hops
- [x] Manual testing for multihop channel handshake with 2+ connection hops

____
#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by romac** [comment]
Done in https://github.com/informalsystems/hermes/pull/4050
