### ISSUE TITLE
gRPC: message length too large

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#4069]
## Version

v1.9

## Steps to Reproduce

![image](https://github.com/informalsystems/hermes/assets/1757002/8d3ebfec-f8bc-4224-bffb-3c8322b4d3c6)

## Acceptance Criteria

- this query hits a chain that has many channels (if I understood correctly, 250'000), so acceptance criteria is to find a way to perform the query successfully

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ljoss17** [comment]
The `tonic` library has a limit on decoding size, https://docs.rs/tonic/latest/tonic/client/struct.Grpc.html#method.max_decoding_message_size, which we increased to `33554432` bytes by default https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/config.rs#L210.

It is possible to increase this limit with the per-chain configuration `max_grpc_decoding_size`. See https://github.com/informalsystems/hermes/issues/3334
