### ISSUE TITLE
Create Homebrew tap for `hermes`

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#678]
## Crate

n/a

## Depends on

- [x] #677

## Summary

Create a [Homebrew tap](https://docs.brew.sh/Taps) for `hermes`.

## Problem Definition

Users would then be able to install `hermes` via Homebrew by running the following commands

```shell
$ brew install informalsystems/software/hermes
```

## Proposal

[Create a Homebrew tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) in a repository named `homebrew-software` (name to be discussed) under the `informalsystems` organization and add a formula for `hermes`.

## Acceptance criteria

- [ ] homebrew tap for `hermes` binary
- [ ] update the Hermes guide to document the installation of Hermes via homebrew

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Tagging @harveenSingh as he can likely tackle this soon.

**Comment by harveenSingh** [comment]
This is a great idea. Will work on it.

**Comment by seanchen1991** [comment]
Closing this in favor of the Mac binary that @harveenSingh has built out in the [euc](https://github.com/informalsystems/euc) repository. 

The main benefit is that the binary is bundled with other pieces of ecosystem tooling and software for easier maintenance across the board. The downside is that users won't be able to download and install Hermes via the `brew install` command; however a Mac binary is perhaps just as professional as a homebrew tap.
