### ISSUE TITLE
Relayer error handling specification

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/hermes#712]
## Crate
docs

## Summary
Currently the relayer performs retries for any error that occurs while building messages and transactions. 

## Problem Definition
There are RPC, light client, on-chain, internal errors, etc. The most complex ones are the on-chain errors that are a bit more subtle (leaving aside errors in the relayer code) and also they are not typed (we just get an error message and the reason is embedded in a string). The retry may apply for some cases, in others we should not retry (e.g. a transaction has already been submitted by another relayer), and yet in other cases we should rebuild stuff, etc.

## Proposal
Analyze the code, document all errors and the actions to be taken in each case. 
Consider also the exponential backoff as per @romac's  https://github.com/informalsystems/ibc-rs/pull/709#discussion_r582852413, where applicable.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
> also they are not typed (we just get an error message and the reason is embedded in a string)

May be worth trying to get these typed upstream in ibc

**Comment by soareschen** [comment]
I tried to do a full trace of an example error message to see how it is propagated. There is a complicated path from the Hermes relayer to the IBC module, and there are many potential errors that can occur in each step. 

On the Go side, the error messages are formatted using helpers such as `sdkerrors.Wrapf` that are converted into strings. It would be challenging to modify the Go code to use more structured logging, so we can only do pattern matching on the string to find the type of error that are of our interest.

Here is an example error message:

> Error: tx error: failed with underlying cause: tx response error: deliver_tx reports error: log=Log("failed to execute message; message index: 1: connection handshake open try failed: failed connection state verification for client (07-tendermint-4): chained membership proof failed to verify membership of value: 0A0F... in subroot C9FE...at index 0. Please ensure the path and value are both correct.: invalid proof")

And here is the manual stack trace:

- `tx error` - [ibc-rs/relayer-cli/src/error.rs:33](https://github.com/informalsystems/ibc-rs/blob/9b3d1a344f1a0e179ef42b48cffba18e593243ee/relayer-cli/src/error.rs#L33)
- `failed with underlying cause` - [ibc-rs/relayer/src/connection.rs:31](https://github.com/informalsystems/ibc-rs/blob/9b3d1a344f1a0e179ef42b48cffba18e593243ee/relayer/src/connection.rs#L31)
- `tx response error` - [ibc-rs/relayer/src/connection.rs:614](https://github.com/informalsystems/ibc-rs/blob/9b3d1a344f1a0e179ef42b48cffba18e593243ee/relayer/src/connection.rs#L614)
- `deliver_tx reports error` - [ibc-rs/relayer/src/chain/cosmos.rs:1472](https://github.com/informalsystems/ibc-rs/blob/9b3d1a344f1a0e179ef42b48cffba18e593243ee/relayer/src/chain/cosmos.rs#L1472)
- `failed to execute message` - [cosmos-sdk/baseapp/baseapp.go:735](https://github.com/cosmos/cosmos-sdk/blob/5725659684fc93790a63981c653feee33ecf3225/baseapp/baseapp.go#L735)
- `connection handshake open try failed` - [ibc-go/modules/core/keeper/msg_server.go:L174](https://github.com/cosmos/ibc-go/blob/6537f248812780adf553a2aca63944607ea32468/modules/core/keeper/msg_server.go#L174)
- `failed connection state verification` - [ibc-go/modules/core/03-connection/keeper/verify.go](https://github.com/cosmos/ibc-go/blob/6537f248812780adf553a2aca63944607ea32468/modules/core/03-connection/keeper/verify.go#L98)
- `chained membership proof failed to verify membership` - [ibc-go/modules/core/23-commitment/types/merkle.go:249](https://github.com/cosmos/ibc-go/blob/6537f248812780adf553a2aca63944607ea32468/modules/core/23-commitment/types/merkle.go#L249)
- `invalid proof` - [ibc-go/modules/core/23-commitment/types/errors.go#L12](https://github.com/cosmos/ibc-go/blob/6537f248812780adf553a2aca63944607ea32468/modules/core/23-commitment/types/errors.go#L12)

I'm not sure if there are good way to document all errors on the Go code, other than trying to search through the code with keywords such as: `sdkerrors.Wrap`, `sdkerrors.Wrapf`, `fmt.Errorf`, and look for standard errors in `ibc-go/modules/*/errors.go`. If we do document the errors, we could submit the documentation to ibc-go as well.

**Comment by ancazamfir** [comment]
we get the response from the Tx here: https://github.com/informalsystems/ibc-rs/blob/2592440b0c599304a1032746ce975b2cf7baa673/relayer/src/chain/cosmos.rs#L1479

The response has a `check_tx` and a `deliver_tx` result with type `TxResult` defined here https://github.com/informalsystems/tendermint-rs/blob/89b3fd0a236b54fcbd149aa9917a52f7d0a6de26/rpc/src/endpoint/broadcast/tx_commit.rs#L61-L91

We currently take the `log` and embed it in an error. I think we are interested in returning some typed errors based on the `code` and let the caller decide if the error is recoverable or not.

For IBC the errors (codes) are defined in the `errors.go` file in each sub-protocol. One example: https://github.com/cosmos/ibc-go/blob/main/modules/core/03-connection/types/errors.go

If I try to send a `chan-open-try` for a connection that is not opened, an error is issued from the chain here (`ErrInvalidConnectionState` which is code 6):
https://github.com/cosmos/ibc-go/blob/f4123347754d814759c9208273fe6772880063cb/modules/core/04-channel/keeper/handshake.go#L154-L158

And we get this response (prinln from our `tx_result_to_event`)

```
Response {
    check_tx: TxResult {
        code: Ok,
        data: None,
        log: Log(
            "[]",
        ),
        info: Info(
            "",
        ),
        gas_wanted: Gas(
            0,
        ),
        gas_used: Gas(
            0,
        ),
        events: [],
        codespace: Codespace(
            "",
        ),
    },
    deliver_tx: TxResult {
        code: Err(
            6,
        ),
        data: None,
        log: Log(
            "failed to execute message; message index: 1: channel handshake open try failed: connection state is not OPEN (got STATE_INIT): invalid connection state",
        ),
        info: Info(
            "",
        ),
        gas_wanted: Gas(
            0,
        ),
        gas_used: Gas(
            0,
        ),
        events: [],
        codespace: Codespace(
            "connection",
        ),
    },
    hash: transaction::Hash(7D51A00CC530011768600E1BF64816D3CB99BE0EBBC1408E7DCC09CC4C9972B7),
    height: block::Height(39444),
}
```

I think we need to look at all ibc `error.rs` files and map the errror `code` -s to hermes typed errors. Not sure if a one-to-one mapping is needed but it is a start.

**Comment by soareschen** [comment]
Yes, that is my impression as well. However the error code are just integers specific to the module, and I am not sure if they are guaranteed to not overlap when making a call. My initial thought was to do string pattern matching to determine the exact error. Also, the Go code do not just use `sdkerrors.Wrapf`, but also other more general functions such as `fmt.Errorf`. We could perhaps try to classify the more prominent errors in the `errors.go` files first, though I don't think they are exhaustive.

So do you mean the main choke point we need to handle is `tx_result_to_event`? This was not specified in the issue description, and I ended up hunting the entire code base and not knowing where the errors of interest are originated from. :sweat_smile:

**Comment by ancazamfir** [comment]
> and I am not sure if they are guaranteed to not overlap when making a call. 

they don't within the `codespace`

> Also, the Go code do not just use sdkerrors.Wrapf, but also other more general functions such as fmt.Errorf

yes, but on the relayer side we are interested in that `code` integer and translate it into a typed error.

> So do you mean the main choke point we need to handle is tx_result_to_event? This was not specified in the issue description, 

Sorry, I should have added more details to `.. most complex ones are the on-chain errors` But looking at the traces you posted it looked to me that you were on the right track.

**Comment by soareschen** [comment]
> they don't within the codespace

Aha! So that's the devil in the detail! Then I'm confident to interpret the error code directly.

Btw I'm still quite confused that when an error happens, `tx_result_to_event` still succeeds with the error event:

```rust
    if response.check_tx.code.is_err() {
        return Ok(vec![IbcEvent::ChainError(format!(
            "check_tx reports error: log={:?}",
            response.check_tx.log
        ))]);
    }
```

Is that intentional? If not I will just change it to return them as newly classified errors in `relayer::errors::Error`.

**Comment by ancazamfir** [comment]
> 
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzUyOTUwOQ==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzUyOTUwOQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MzUyOTUwOQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-843529509" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists" data-body-version="63892f5bd73b5f037664c6f2b7ae2b3dd60d61272c3d1778d000e1576db1087d" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Is that intentional? If not I will just change it to return them as newly classified errors in&nbsp;relayer::errors::Error.</task-lists></div><form class="js-comment-update" id="issuecomment-843529509-edit-form" action="https://github.com/informalsystems/ibc-rs/issue_comments/843529509" accept-charset="UTF-8" method="post" form_signature="2517038504825648725" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDE3OkRlbWlsZXN0b25lZEV2ZW50NDc5MTk2NDIyMQ==" style="box-sizing: border-box;"><div class="TimelineItem js-targetable-element" data-team-hovercards-enabled="" id="event-4791964221" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class="TimelineItem-badge " style="box-sizing: border-box; position: relative; z-index: 1; display: flex; width: 32px; height: 32px; margin-right: 8px; margin-left: -15px; color: var(--color-icon-secondary); align-items: center; background-color: var(--color-timeline-badge-bg); border: 2px solid var(--color-bg-canvas); border-radius: 50%; justify-content: center; flex-shrink: 0; font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><svg class="octicon octicon-milestone" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.75 0a.75.75 0 01.75.75V3h3.634c.414 0 .814.147 1.13.414l2.07 1.75a1.75 1.75 0 010 2.672l-2.07 1.75a1.75 1.75 0 01-1.13.414H8.5v5.25a.75.75 0 11-1.5 0V10H2.75A1.75 1.75 0 011 8.25v-3.5C1 3.784 1.784 3 2.75 3H7V.75A.75.75 0 017.75 0zm0 8.5h4.384a.25.25 0 00.161-.06l2.07-1.75a.25.25 0 000-.38l-2.07-1.75a.25.25 0 00-.161-.06H2.75a.25.25 0 00-.25.25v3.5c0 .138.112.25.25.25h5z"></path></svg></div><br class="Apple-interchange-newline"></div></div>

that's our current way to distinguish between chain IBC errors and all the rest. There are very few for which we should retry here but we need to go over the full list of IBC SdkErrors first. And yes we can work with typed errors here also.

**Comment by adizere** [comment]
Seems like we have some dead code capturing various errors that come from IBC-go. Ref: https://github.com/informalsystems/ibc-rs/pull/2266#issuecomment-1145951834

**Comment by ancazamfir** [comment]
Closing as most of the work has been done in https://github.com/informalsystems/hermes/pull/988 and other PRs over the years. Let' reopen if needed.
