### ISSUE TITLE
Data-driven relaying loop and handshakes

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#765]
## Crate

`ibc-relayer`

## Summary

Refactor the relaying loop and handshake code into a FSM-like data-driven pipeline with better separation between domain logic and I/O for better testing and introspection.

## Problem Definition

The way the relaying loop and handshake code currently performs I/O in the form of chain and light client queries interleaved with the domain logic (ie. validation, proof verification, building of messages) is not very modular and lacks clear separation of concerns which prevents it to be thoroughly tested with unit-tests (eg. via the `MockChain`) and model-based tests (via `modelator`).

## Proposal

Establish a clear separation of concerns by refactoring this code into a finite-state machine or a data-driven pipeline where I/O and domain logic are cleanly delimited in separate actions/stages.

> To be refined further

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
I suspect this is superseded by #2478  ? Will let @romac or @soareschen close if so.
