### ISSUE TITLE
Move `ibc-rs` repository to `cosmos` organization

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/hermes#880]
To facilitate discovery of this repo within the Cosmos world, and since it's becoming core to Cosmos dev (especially Hermes), we should move this repo to https://github.com/cosmos/.

In principle this is a simple transfer operation and Github will handle redirects, but to avoid any potential breaks to existing workflows right now, we will target end of ~~June~~ July for this (ie. after DeX launch :) )

**Comment by adizere** [comment]
Superseded by #2639.
